#!/bin/csh

if ( "$2" == "" ) then
    echo "Usage: CB_CopyOldFiles oldPoolDir newPoolDir"
    echo "copies all files from an old local source pool to a new local source pool"
    exit 1
endif

echo Copying files
cd $1
foreach f ( `find . -type f -print` )
    echo Copying $f
    mkdir -p $2/`dirname $f`
    /bin/cp -p $f $2/$f
end

echo Copying symbolic links
foreach f ( `find . -type l ! -name SCCS -print` )
    echo Copying $f
    mkdir -p $2/`dirname $f`
    /opt/gnu/bin/cp -d $f $2/$f
end


