#!/bin/sh
#
# Dieses Skript erstellt die Dependencies fuer C- und C++-Dateien
# Die Parameter sind CFLAGS, INCLUDE-Anweisungen und Dateien, die direkt an
# gcc weiter gereicht werden. Die Ausgabe von gcc wird dann noch so 
# ueberarbeitet, dass fuer die lokalen Dateien deren Pfad entfernt
# wird. Diese Dateien werden bei gmake ueber vpath wieder gefunden.
#

gcc -MM $* > depend.mk.bak

DEP=

rm -f depend.mk
touch depend.mk

for f in `cat depend.mk.bak`
do
	if (echo $f | egrep "(^\.\./.*|^src/.*|^\./.*)" > /dev/null); then
		DEP="$DEP `basename $f` "
	else
		if (echo $f | egrep "^*\.o:" > /dev/null); then
			echo $DEP >> depend.mk
			DEP=`echo objects/$f src/../objects/$f \\ | sed s/://1`
		else
		    if (echo $f | egrep '\\' > /dev/null); then
				echo > /dev/null
			else
				DEP="$DEP $f"
			fi
		fi
	fi
done


echo $DEP >> depend.mk

rm -f depend.mk.bak
