#!/bin/sh
# This script creates the system files for ConceptBase.
# It starts a CBserver with the smallest possible database (produced by transformSML0)
# and tells the system via CB_TestClient and the script SYSTEM to
# the server. After that, the server is stopped and the log files of the TestClient
#
# Call: CB_Create_SYSTEM  [-i]
#  with parameter -i, the script SYSTEM-i.cbs (latest interactive CBserver)
#  will be used, otherwise the script SYSTEM.cbs is used (regular CBserver)
#

CB_VARIANT=`CBvariant`
TESTCLIENT_DIR=/home/cbase/CB_NewStruct/CB_Admin/utils/CB_TestClient
PROLOG_VARIANT=${PROLOG_VARIANT:=SWI}
CB_POOL=$CB_WORK
DATABASE=SYSTEM
SRCDIR=$CB_POOL/lib/
CB_PORTNR=${CB_PORTNR:=6498}
SCRIPTFILE=$SRCDIR/testSML1.cbs

export CB_PORTNR

# these two files have been created from SML0.prop by transfomSML0
cp SYSTEM_SML0.telos SYSTEM.telos
cp SYSTEM_SML0.symbol SYSTEM.symbol

# If the DATABASE directory exists, then delete it to have a fresh init
if [ -d $DATABASE ]; then
	echo rm -f $DATABASE/OB.*
	rm -f $DATABASE/OB.*
else
	mkdir $DATABASE
fi

# Move the files with the most basic system objects to the DATABASE directory
mv SYSTEM.telos $DATABASE/OB.telos
mv SYSTEM.symbol $DATABASE/OB.symbol

# These files must exist for the CBserver but can be empty 
touch $DATABASE/OB.rule
touch $DATABASE/OB.ruleinfo
touch $DATABASE/OB.ecarule


