#!/bin/sh
# This script transforms the very basic system objects of SML0.prop
# into the internal format in files SYSTEM_SML0.telos and
# SYSTEM_SML0.symbol
#
# Call: transformSML0
#

CB_VARIANT=`CBvariant`
PROLOG_VARIANT=${PROLOG_VARIANT:=SWI}
CB_POOL=$CB_WORK
# TRANSFORM points to the platform-specific binary of transform
# Create it with a 'CB_Make all' in $CB_POOL/serverSources/C_Files/libCOS3 
TRANSFORM=$CB_POOL/$CB_VARIANT/serverSources/C_Files/libCos3/objects.${PROLOG_VARIANT}/transform


export CB_PORTNR

# Create SYSTEM.telos and SYSTEM.symbol from SML0.prop
rm -f SYSTEM.telos SYSTEM.symbol
touch SYSTEM.telos
touch SYSTEM.symbol
echo $TRANSFORM  $CB_POOL/lib/SML0.prop
$TRANSFORM  $CB_POOL/lib/SML0.prop

if [ $? != 0 ]; then
    echo transform failed
    exit 1
fi

# memorize the result in files used by CB_Create_SYSTEM
cp SYSTEM.telos SYSTEM_SML0.telos
cp SYSTEM.symbol SYSTEM_SML0.symbol



