# Resolve libcb* dependencies: Nix (find_package + CMAKE_PREFIX_PATH) or monorepo siblings.
include_guard(GLOBAL)

function(libcb_find_general)
  find_package(libcbgeneral CONFIG QUIET)
  if(NOT libcbgeneral_FOUND)
    include("${CMAKE_CURRENT_LIST_DIR}/LibcbIncludeDirs.cmake")
  endif()
endfunction()

function(libcb_link_general target scope)
  if(TARGET ConceptBase::libcbgeneral)
    target_link_libraries(${target} ${scope} ConceptBase::libcbgeneral)
  elseif(TARGET ConceptBase::cbgeneral)
    target_link_libraries(${target} ${scope} ConceptBase::cbgeneral)
  else()
    target_include_directories(${target} ${scope} ${LIBCBGENERAL_INCLUDE_DIR})
  endif()
endfunction()

function(libcb_find_telos)
  find_package(libcbtelos CONFIG QUIET)
  if(NOT libcbtelos_FOUND)
    include("${CMAKE_CURRENT_LIST_DIR}/LibcbIncludeDirs.cmake")
  endif()
endfunction()

function(libcb_link_telos target scope)
  if(TARGET ConceptBase::libcbtelos)
    target_link_libraries(${target} ${scope} ConceptBase::libcbtelos)
  elseif(TARGET ConceptBase::cbtelos)
    target_link_libraries(${target} ${scope} ConceptBase::cbtelos)
  else()
    target_include_directories(${target} ${scope} ${LIBCBTELOS_INCLUDE_DIR})
  endif()
endfunction()

function(libcb_find_cbc)
  find_package(libcbc CONFIG QUIET)
  if(NOT libcbc_FOUND)
    include("${CMAKE_CURRENT_LIST_DIR}/LibcbIncludeDirs.cmake")
  endif()
endfunction()

function(libcb_link_cbc target scope)
  if(TARGET ConceptBase::libcbc)
    target_link_libraries(${target} ${scope} ConceptBase::libcbc)
  elseif(TARGET ConceptBase::cbc)
    target_link_libraries(${target} ${scope} ConceptBase::cbc)
  else()
    target_include_directories(${target} ${scope} ${LIBCBC_INCLUDE_DIR})
  endif()
endfunction()
