{ stdenv, cbserver, cbshell, howtosRoot, lib, ... }@args:

let
  call = file: import file args;
  slugs = [
    "analyze-document-flows"
    "analyze-graphs"
    "associate-cbgraph-to-graph-files-gel"
    "avoid-traps-with-aggregation-functions-in-constraints"
    "batch-load-multiple-files-in-conceptbase"
    "capture-some-semantics-of-petri-nets"
    "create-deeptelos-models"
    "create-large-test-models"
    "deal-with-multi-sets"
    "deal-with-ocl-style-invariants"
    "define-active-rules"
    "define-and-use-functions"
    "define-basic-properties-of-relations"
    "define-co-variant-specialization"
    "define-customized-error-messages-for-integrity-constraints"
    "define-formulas-at-the-meta-class-level"
    "define-object-specific-graphical-properties"
    "define-recursive-queries-on-cyclic-structures"
    "define-set-operators"
    "define-simple-rules-and-constraints"
    "define-time-points"
    "define-your-own-axioms"
    "design-customized-answer-formats-for-queries"
    "design-service-networks"
    "export-models-as-graphviz-specifications"
    "formalize-process-data-diagrams"
    "formulate-query-calls-with-other-queries-as-parameters"
    "generate-business-models"
    "handle-explicit-attribution-and-default-values"
    "inspect-the-object-base-as-a-whole"
    "install-conceptbase-on-raspberry-pi-2"
    "integrate-cbshell-with-regular-scripts"
    "interact-with-conceptbase-from-the-command-line"
    "manage-access-rights-to-modules-and-other-resources"
    "materialize-graphical-views"
    "materialize-query-results-as-files"
    "miscellaneous"
    "model-clabjects"
    "model-event-process-chains-epcs"
    "model-the-entity-relationship-model"
    "optimize-conditions-in-eca-rules"
    "realize-cascading-untell-via-ecarules"
    "reason-about-the-existence-of-santa-claus"
    "reify-query-calls"
    "save-telos-models"
    "send-an-email-via-an-active-rule"
    "specify-resizable-shapes"
    "understand-mof-vs-telos"
    "use-graphical-types"
    "use-query-classes-in-rules-and-constraints"
    "visualize-module-structures"
  ];
  ticketChecks = call ./scripts-to-tests-solutions-to-tickets.nix;
in
  lib.foldl' (acc: slug: acc // call (./. + "/${slug}.nix")) ticketChecks slugs
