#!/usr/bin/env python3
"""Remove leftover LaTeX markup from Typst chapter files under components/doc/."""

from __future__ import annotations

import re
import sys
from pathlib import Path

DOC_ROOT = Path(__file__).resolve().parents[2] / "components/doc"


def slug_from_label(label: str) -> str:
    return label.strip()


def convert_latex_to_typst(text: str) -> str:
    # Drop migration failure markers and LaTeX preambles accidentally inlined.
    text = re.sub(r"^// section conversion failed\s*\n", "", text, flags=re.M)
    text = re.sub(
        r"^// section conversion failed\s*\n\\documentclass.*?(?=^= |\Z)",
        "",
        text,
        flags=re.M | re.S,
    )
    text = re.sub(
        r"^\\documentclass\[.*?(?=^= |\Z)",
        "",
        text,
        flags=re.M | re.S,
    )

    text = re.sub(
        r"\\chapter\{([^}]*)\}\s*\n\\label\{([^}]*)\}",
        lambda m: f"= {m.group(1).strip()}\n<{slug_from_label(m.group(2))}>\n",
        text,
    )
    text = re.sub(
        r"\\chapter\{([^}]*)\}",
        lambda m: f"= {m.group(1).strip()}\n",
        text,
    )
    text = re.sub(
        r"\\section\{([^}]*)\}\s*\n\\label\{([^}]*)\}",
        lambda m: f"== {m.group(1).strip()}\n<{slug_from_label(m.group(2))}>\n",
        text,
    )
    text = re.sub(
        r"\\section\{([^}]*)\}",
        lambda m: f"== {m.group(1).strip()}\n",
        text,
    )
    text = re.sub(
        r"\\subsection\{([^}]*)\}\s*\n\\label\{([^}]*)\}",
        lambda m: f"=== {m.group(1).strip()}\n<{slug_from_label(m.group(2))}>\n",
        text,
    )
    text = re.sub(
        r"\\subsection\{([^}]*)\}",
        lambda m: f"=== {m.group(1).strip()}\n",
        text,
    )
    text = re.sub(
        r"\\subsubsection\{([^}]*)\}",
        lambda m: f"==== {m.group(1).strip()}\n",
        text,
    )
    text = re.sub(r"\\label\{([^}]*)\}", lambda m: f"<{slug_from_label(m.group(1))}>", text)

    text = re.sub(
        r"\\ref\{([^}]*)\}",
        lambda m: f'section #raw("{m.group(1)}")',
        text,
    )
    text = re.sub(
        r"\\cite\{([^}]*)\}",
        lambda m: " ".join(f"@{k.strip()}" for k in m.group(1).split(",")),
        text,
    )
    text = re.sub(
        r"\\url\{([^}]*)\}",
        lambda m: f'#link("{m.group(1).strip()}")',
        text,
    )

    def em_repl(m: re.Match[str]) -> str:
        inner = m.group(1).replace(r"\/", "").strip()
        return f"*{inner}*"

    text = re.sub(r"\{\\em\s+([^}]*)\}", em_repl, text)
    text = re.sub(r"\{\\em\s+([^}]*)\/\}", em_repl, text)

    def tt_repl(m: re.Match[str]) -> str:
        inner = m.group(1).strip().replace("\\", "\\\\").replace('"', '\\"')
        return f'#raw("{inner}")'

    text = re.sub(r"\{\\tt\s+([^}]*)\}", tt_repl, text)

    def quote_repl(m: re.Match[str]) -> str:
        body = m.group(1).strip()
        return f"#quote(block: true)[\n{body}\n]"

    text = re.sub(r"\\begin\{quote\}(.*?)\\end\{quote\}", quote_repl, text, flags=re.S)

    def verb_repl(m: re.Match[str]) -> str:
        body = m.group(1).strip("\n")
        return f"```\n{body}\n```"

    text = re.sub(r"\\begin\{verbatim\}(.*?)\\end\{verbatim\}", verb_repl, text, flags=re.S)

    text = re.sub(r"\\\\\s*$", "", text, flags=re.M)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = fix_typst_backticks(text)
    text = wrap_telos_dollar_blocks(text)
    text = fix_graphviz_and_tell_blocks(text)
    return text


def fix_graphviz_and_tell_blocks(text: str) -> str:
    """Keep Graphviz listings and tell-blocks as unparsed raw text."""

    def raw_block(body: str) -> str:
        body = body.strip("\n")
        body = (
            body.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
        )
        return f'#text(raw("{body}"))'

    text = re.sub(
        r"(?ms)^tell '\n.*?^\s*'\s*$",
        lambda m: raw_block(m.group(0)),
        text,
    )
    text = re.sub(
        r"(?ms)^# Generated by ConceptBase[^\n]*\n"
        r"(?:#.*\n)*"
        r"digraph[^\n]*\n"
        r"(?:.*\n)*?"
        r"fontsize=12;\n",
        lambda m: raw_block(m.group(0)),
        text,
    )
    return text


def wrap_telos_dollar_blocks(text: str) -> str:
    """Escape $...$ in Telos frames so Typst does not enter math mode."""

    text = unwrap_raw_block_markers(text)

    telos_start = re.compile(
        r"^(\s*(?:- )?)([A-Z][A-Za-z0-9_]* (?:with|in Class)|QueryClass )"
    )
    formula = re.compile(r"\$\s*(?:forall|exists|\(|~|not )")

    lines = text.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        m = telos_start.match(line)
        if m and formula.search("\n".join(lines[i : min(i + 40, len(lines))])):
            block: list[str] = []
            j = i
            while j < len(lines):
                block.append(lines[j])
                if lines[j].strip() == "end":
                    j += 1
                    break
                j += 1
            if any(formula.search(b) for b in block):
                if i > 0 and lines[i - 1].strip() == "-":
                    out.append("- ")
                for b in block:
                    out.append(re.sub(r"(?<!\\)\$", r"\\$", b))
                i = j
                continue
        out.append(line)
        i += 1
    return "\n".join(out)


def unwrap_raw_block_markers(text: str) -> str:
    """Remove #raw(block: true)[ wrappers that still parse Typst markup."""

    lines = text.splitlines()
    out: list[str] = []
    for line in lines:
        s = line.strip()
        if s in {"#raw(block: true)[", "- #raw(block: true)["}:
            continue
        out.append(line)
    # Drop closing brackets immediately after a lone `end` line.
    cleaned: list[str] = []
    for line in out:
        if line.strip() == "]" and cleaned and cleaned[-1].strip().endswith("end"):
            continue
        cleaned.append(line)
    return "\n".join(cleaned)


def fix_typst_backticks(text: str) -> str:
    """Convert pandoc markdown `code` spans to Typst #raw("code")."""

    def repl(m: re.Match[str]) -> str:
        inner = m.group(1).replace("\\", "\\\\").replace('"', '\\"')
        return f'#raw("{inner}")'

    prev = None
    while prev != text:
        prev = text
        text = re.sub(r"`([^`\n]+)`", repl, text)
    # Drop stray opening backticks (unpaired pandoc artifacts).
    text = re.sub(r"(?<![`])`(?![`])", "", text)
    return text


def fix_otelos_axioms(text: str) -> str:
    """Replace raw LaTeX math lines with Typst math (axioms 10–24)."""

    replacements = [
        (
            r'\$\\forall \~c \~\\textit\{In\}\(c,\\hbox\{\\\#Obj\}\) \\Rightarrow \\textit\{Isa\}\(c,c\)\$',
            '$forall c med italic("In")(c, "#Obj") arrow.r.double italic("Isa")(c, c)$',
        ),
        (
            r'\$\\forall \~o,x,n,y \~\(P\(o,x,n,y\) \\Leftrightarrow\s+\\textit\{In\}\(o,\\hbox\{\\\#Obj\}\)\)\$',
            '$forall o, x, n, y med P(o, x, n, y) arrow.l.r.double italic("In")(o, "#Obj")$',
        ),
        (
            r'\$\\forall \~o,n \~\(P\(o,o,n,o\) \\land \(n \\ne in\) \\land \(n \\ne isa\) \\Leftrightarrow\s+\\textit\{In\}\(o,\\hbox\{\\\#Indiv\}\)\)\$',
            '$forall o, n med P(o, o, n, o) and (n != "in") and (n != "isa") arrow.l.r.double italic("In")(o, "#Indiv")$',
        ),
        (
            r'\$\\forall \~o,x,c \~\(P\(o,x,in,c\) \\land \(o \\ne x\) \\land \(o \\ne c\) \\Leftrightarrow\s+\\textit\{In\}\(o,\\hbox\{\\\#Inst\}\)\)\$',
            '$forall o, x, c med P(o, x, "in", c) and (o != x) and (o != c) arrow.l.r.double italic("In")(o, "#Inst")$',
        ),
        (
            r'\$\\forall \~o,c,d \~\(P\(o,c,isa,d\) \\land \(o \\ne c\) \\land \(o \\ne d\) \\Leftrightarrow\s+\\textit\{In\}\(o,\\hbox\{\\\#Spec\}\)\)\$',
            '$forall o, c, d med P(o, c, "isa", d) and (o != c) and (o != d) arrow.l.r.double italic("In")(o, "#Spec")$',
        ),
        (
            r'\$\\forall \~o,x,n,y \~\(P\(o,x,n,y\) \\land \(o \\ne x\) \\land \(o \\ne y\) \\land\s+\(n \\ne in\) \\land \(n \\ne isa\)\s+\\Leftrightarrow \\textit\{In\}\(o,\\hbox\{\\\#Attr\}\)\)\$',
            '$forall o, x, n, y med P(o, x, n, y) and (o != x) and (o != y) and (n != "in") and (n != "isa") arrow.l.r.double italic("In")(o, "#Attr")$',
        ),
        (
            r'\$\\forall \~o \~\\textit\{In\}\(o,\\hbox\{\\\#Obj\}\) \\Rightarrow\s+\\textit\{In\}\(o,\\hbox\{\\\#Indiv\}\) \\lor\s+\\textit\{In\}\(o,\\hbox\{\\\#Inst\}\) \\lor\s+\\textit\{In\}\(o,\\hbox\{\\\#Spec\}\) \\lor\s+\\textit\{In\}\(o,\\hbox\{\\\#Attr\}\)\$',
            '$forall o med italic("In")(o, "#Obj") arrow.r.double italic("In")(o, "#Indiv") or italic("In")(o, "#Inst") or italic("In")(o, "#Spec") or italic("In")(o, "#Attr")$',
        ),
        (
            r'\$P\(\\\#Obj,\\\#Obj,\\hbox\{Proposition\},\\\#Obj\)\$',
            '$P("#Obj", "#Obj", "Proposition", "#Obj")$',
        ),
        (
            r'\$P\(\\\#Indiv,\\\#Indiv,\\hbox\{Individual\},\\\#Indiv\)\$',
            '$P("#Indiv", "#Indiv", "Individual", "#Indiv")$',
        ),
        (
            r'\$P\(\\\#Attr,\\\#Obj,\\hbox\{attribute\},\\\#Obj\)\$',
            '$P("#Attr", "#Obj", "attribute", "#Obj")$',
        ),
        (
            r'\$P\(\\\#Inst,\\\#Obj,\\hbox\{InstanceOf\},\\\#Obj\)\$',
            '$P("#Inst", "#Obj", "InstanceOf", "#Obj")$',
        ),
        (
            r'\$P\(\\\#Spec,\\\#Obj,\\hbox\{IsA\},\\\#Obj\)\$',
            '$P("#Spec", "#Obj", "IsA", "#Obj")$',
        ),
    ]
    for pat, rep in replacements:
        text = re.sub(pat, rep, text, flags=re.S)
    return text


def process_file(path: Path) -> bool:
    original = path.read_text(encoding="utf-8")
    updated = convert_latex_to_typst(original)
    if path.name == "O-Telos-Axioms.typ":
        updated = fix_otelos_axioms(updated)
    if updated != original:
        path.write_text(updated, encoding="utf-8")
        return True
    return False


def main() -> int:
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else DOC_ROOT
    changed = 0
    for typ in sorted(root.rglob("*.typ")):
        if process_file(typ):
            print(f"cleaned {typ.relative_to(root)}")
            changed += 1
    print(f"done ({changed} files updated)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
