# AWK script to extract information about registered users
# from Mail file "cb-requests" which contains all mails which
# have been generated by the online registration form

BEGIN { n = 0; FS=" ";}

{ if($1=="Date:") n=2; }
{ if (n==13) { printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n",name,uni,str,city,land,email,date,zweck,cbv; n=0;}}

{ if (n==12) { cbv=$3; n++; }}     # Versionsnummer
{ if (n==11) n++; } 				# Leerzeile
{ if (n==10) { zweck=$0; n++; }} 	# Verwendungszweck
{ if (n==9) { email=$0; n++; }} 	# Email
{ if (n==8) { land=$0; n++; }} 		# Land
{ if (n==7) { city=$0; n++; }} 		# Stadt
{ if (n==6) { str=$0; n++; }} 		# Strasse
{ if (n==5) { name=$0; n++; }} 		# Name
{ if (n==4) { uni=$0; n++; }} 		# Universitaet
{ if (n==3) n++; } 					# Leerzeile
{ if (n==2) { if($7~/19/) { year = $7; } else {year=$6;} date=sprintf("%s.%s.%s",$3,$2,year); n++; }} 		# Datum
{ if (n==1) n++; } 					# Leerzeile

$1~/Content-Length:/ { n=1; }
$1~/content-length:/ { n=1; }
