#!/bin/sh
#
# Script to install ConceptBase
#

version=$2

instdir=
currdir=`pwd`
file_prefix=cb$version

install_file=${file_prefix}

programs="sed tar gunzip"

unpackfile=
unpackerror=0
install_ok=0

# ---------------
# change_inst_dir
# ---------------

change_inst_dir()
{
	if [ ! -d $dir ]
	then
		echo $dir does not exist!
		echo I try to create it.
		mkdir $dir
		if [ ! -d $dir ]
		then
			echo Cannot create $dir
		else
			echo $dir created.
			cd $dir
			instdir=`pwd`
			cd $currdir
		fi
	else
		cd $dir
		instdir=`pwd`
		cd $currdir
	fi
}


# ---------------
# unpack_targz
# ---------------

unpack_targz()
{

	if [ -f ${unpackfile}.tar.gz ]
	then
		echo Unzipping ${unpackfile}.tar.gz
		gunzip -c ${unpackfile}.tar.gz | tar -xvf -
	else
		echo ${unpackfile}.tar.gz not found!
		unpackerror=1
	fi
}

# ---------------
# install_cb
# ---------------

install_cb()
{
	echo Installing ConceptBase to $instdir
	cd $instdir

	unpackfile=$currdir/$install_file
	unpack_targz

	if [ "$unpackerror" = "0" ]
	then
		if [ -f bin/CBserver ]
		then
			mv bin/CBserver bin/CBserver.bak
			sed "s!~cbase/CB_[^/]*/CB_Product!${instdir}!g" bin/CBserver.bak > bin/CBserver
			chmod 755 bin/CBserver
			rm -f bin/CBserver.bak
		fi

		if [ -f bin/CBjavaInterface ]
		then
			mv bin/CBjavaInterface bin/CBjavaInterface.bak
			sed "s!/home/CBase/CB_[^/]*/CB_Product!${instdir}!g"  bin/CBjavaInterface.bak > bin/CBjavaInterface
			chmod 755 bin/CBjavaInterface
			ln -s CBjavaInterface bin/CBinterface
			rm -f bin/CBjavaInterface.bak
		fi

		echo Installation complete.
		install_ok=1

		cd $currdir
	fi
}

# -------------
# exit_install
# -------------

exit_install()
{

	if [ "$install_ok" = "1" ]
	then
		echo Before ConceptBase can be started, you need to register.
		echo Further Information can be found in the Installation Guide.
		exit
	else
		echo Installation was not successful!
		echo Please rerun the installation script!
	fi
}

# --------------
# test_tarfiles
# --------------

test_tarfiles()
{
	if [ ! -f ${install_file}.tar.gz ]
	then
		echo ${install_file}.tar.gz not found!
		echo You must get this file to run ConceptBase.
		echo Start CB_install in the directory where
		echo the tar.gz-files are located
		exit 1
	fi
}


# ----------------
# check_programs
# ----------------

check_programs()
{
	for prog in $programs
	do
		if which $prog > /dev/null
		then
			echo $prog found
		else
			echo $prog not found.
			echo You need $prog to install ConceptBase.
			exit 1
		fi
	done
}




# ==============
# MAIN Programm
# ==============


if [ "$2" = "" ]
then
	echo Usage: CBinstall directory version
        echo 'where version is the version number of the CB package to install'
        echo 'e.g. for package cb524.tar.gz the version number is 524'
	echo 'and directory is the directory where CB should be installed'
	exit 1
else
	dir=$1
fi

#check_programs
test_tarfiles

echo ConceptBase installation script
echo ===============================
echo
echo ConceptBase will be installed to directory: $dir
echo

change_inst_dir
install_cb
exit_install
