/*
The ConceptBase.cc Copyright

Copyright 1987-2019 The ConceptBase Team. All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice, this list of
      conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice, this list of
      conditions and the following disclaimer in the documentation and/or other materials
      provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE CONCEPTBASE TEAM ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE CONCEPTBASE TEAM OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those of the authors
and should not be interpreted as representing official policies, either expressed or implied,
of the ConceptBase Team.


The ConceptBase Team is represented by

Manfred Jeusfeld, University of Skovde, 54128 Skovde, Sweden
Matthias Jarke, RWTH Aachen, Informatik 5, Ahornstr. 55, 52056 Aachen, Germany
Christoph Quix, RWTH Aachen, Informatik 5, Ahornstr. 55, 52056 Aachen, Germany


This license is a FreeBSD-style copyright license.
Legal home of the FreeBSD copyright license: http://www.freebsd.org/copyright/freebsd-license.html
*/
/* Generated By:JavaCC: Do not edit this line. TelosParserConstants.java */
package i5.cb.telos.frame;

public interface TelosParserConstants {

  int EOF = 0;
  int IN = 9;
  int ISA = 10;
  int WITH = 11;
  int END = 12;
  int END_PT = 13;
  int IN_CML = 14;
  int ISA_CML = 15;
  int WITH_CML = 16;
  int END_CML = 17;
  int SELECTOR1 = 18;
  int SELECTOR2 = 19;
  int SELECTORB = 20;
  int SCOPERES = 21;
  int ALPHANUM = 30;
  int Num = 31;
  int NUMBER = 32;
  int LABEL = 33;
  int STRINGLABEL = 41;
  int RULELABEL = 43;

  int DEFAULT = 0;
  int PT = 1;
  int CML = 2;
  int WithinComment = 3;
  int WithinString = 4;
  int WithinRule = 5;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"{$set syntax=PlainAachen}\"",
    "\"{$set syntax=PlainToronto}\"",
    "\"{$set syntax=CML}\"",
    "\"in\"",
    "\"isA\"",
    "\"with\"",
    "\"end\"",
    "\"end\"",
    "\"IN\"",
    "\"ISA\"",
    "\"WITH\"",
    "\"END\"",
    "<SELECTOR1>",
    "<SELECTOR2>",
    "<SELECTORB>",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"/\"",
    "<ALPHANUM>",
    "<Num>",
    "<NUMBER>",
    "<LABEL>",
    "\"\\\"\"",
    "\"$\"",
    "\"}\"",
    "<token of kind 37>",
    "<token of kind 38>",
    "\"\\\\\\\"\"",
    "\"\\\\\\\\\"",
    "\"\\\"\"",
    "<token of kind 42>",
    "\"$\"",
  };

}
