/*
The ConceptBase.cc Copyright

Copyright 1987-2025 The ConceptBase Team. All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice, this list of
      conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice, this list of
      conditions and the following disclaimer in the documentation and/or other materials
      provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE CONCEPTBASE TEAM ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE CONCEPTBASE TEAM OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those of the authors
and should not be interpreted as representing official policies, either expressed or implied,
of the ConceptBase Team.


The ConceptBase Team is represented by

Manfred Jeusfeld, University of Skovde, 54128 Skovde, Sweden


This license is a FreeBSD-style copyright license.
Legal home of the FreeBSD copyright license: http://www.freebsd.org/copyright/freebsd-license.html
*/
/*
 * AddNodeDialog.java
 *
 * Created on 20. M?rz 2002, 10:56
 */
package i5.cb.graph.cbeditor.components;
import i5.cb.CBConfiguration;
import i5.cb.graph.cbeditor.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

/** A dialog which is shown when the user wants to add a new {@link i5.cb.graph.diagram.DiagramNode}
 *
 * @author Schoeneb
 */
public class AddNodeDialog extends javax.swing.JDialog {
    CBFrame m_activeFrame;
    CBEditor m_cbEditor;
    /** Creates new form AddNodeDialog
     * @param cbEditor
     * @param activeFrame
     */
    public AddNodeDialog(java.awt.Frame cbEditor, CBFrame activeFrame) {
        super(cbEditor, true);
        initComponents();
        m_cbEditor = (CBEditor)cbEditor;
        m_activeFrame = activeFrame;
        ResourceBundle bundle = ResourceBundle.getBundle(CBConstants.CB_BUNDLE_NAME);
        setTitle(bundle.getString("AddNodedialog_title") );
        m_addLabel.setText(bundle.getString("AddNodeDialog_objectName") );
        m_addButton.setText(bundle.getString("AddNodeDialog_add") );
        String[] items = CBConfiguration.getStartingObjects(activeFrame.getHost(), activeFrame.getPort() );
        if(items.length>0) {
            m_jtfObject.setText(items[0]);
        }
        ActionListener al=new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                handleButtonPressed(evt);
            }
        };
        m_addButton.addActionListener(al);
        m_jtfObject.addActionListener(al);
        setLocation(300,300);
        pack();
    }

    private void handleButtonPressed(ActionEvent evt){
        if(CBUtil.createAndAddNewDiagramObject(m_jtfObject.getText(), m_activeFrame, null)){
            dispose();
        }
        else{
            ResourceBundle bundle = m_cbEditor.getCBBundle();
            JOptionPane.showMessageDialog(
            m_cbEditor, bundle.getString("Error_NoTelosObjectFound") + " " + m_jtfObject.getText());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        m_addButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        m_addLabel = new javax.swing.JLabel();
        m_jtfObject = new javax.swing.JTextField("Class",20);

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        m_addButton.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(m_addButton, gridBagConstraints);

        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        m_addLabel.setText("jLabel1");
        jPanel1.add(m_addLabel);

        m_jtfObject.setEditable(true);
        jPanel1.add(m_jtfObject);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

    }//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel m_addLabel;
    private javax.swing.JButton m_addButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField m_jtfObject;
    // End of variables declaration//GEN-END:variables

}
