/*
The ConceptBase.cc Copyright

Copyright 1987-2024 The ConceptBase Team. All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice, this list of
      conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice, this list of
      conditions and the following disclaimer in the documentation and/or other materials
      provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE CONCEPTBASE TEAM ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE CONCEPTBASE TEAM OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those of the authors
and should not be interpreted as representing official policies, either expressed or implied,
of the ConceptBase Team.


The ConceptBase Team is represented by

Manfred Jeusfeld, University of Skovde, 54128 Skovde, Sweden


This license is a FreeBSD-style copyright license.
Legal home of the FreeBSD copyright license: http://www.freebsd.org/copyright/freebsd-license.html
*/
/*
 * ConfigQueryParamsDialog.java
 *	
 * Created on 18. March 2002, 11:28
 */

package i5.cb.graph.cbeditor.components;

import i5.cb.telos.object.*;

import java.util.Enumeration;

import javax.swing.*;

/**
 *
 * @author  Schoeneb
 */
class ConfigQueryParamsDialog extends javax.swing.JDialog {

	private i5.cb.telos.object.ObjectBaseInterface m_obi;

	private i5.cb.telos.object.Individual m_telosQuery;

	/** This class is currently not used in the cbeditor!
         * Creates new form ConfigQueryParamsDialog
         * @param parent
         * @param obi
         * @param to  */
	public ConfigQueryParamsDialog(java.awt.Frame parent, ObjectBaseInterface obi, TelosObject to) {
		super(parent, true);
		m_obi = obi;
		m_telosQuery = (Individual)to;
		initComponents();
		addParams();
		pack();	
		setVisible(true);
	
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents
		m_paramContainer = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		m_paramPanel = new javax.swing.JPanel();
		m_buttonPanel = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();

		addWindowListener(new java.awt.event.WindowAdapter() {
			                  public void windowClosing(java.awt.event.WindowEvent evt) {
				                  closeDialog(evt);
			                  }
		                  });

		m_paramContainer.setBorder(new javax.swing.border.EtchedBorder());
		jScrollPane1.setViewportView(m_paramPanel);

		m_paramContainer.add(jScrollPane1);

		getContentPane().add(m_paramContainer, java.awt.BorderLayout.CENTER);

		jButton1.setText("Add query");
		m_buttonPanel.add(jButton1);

		getContentPane().add(m_buttonPanel, java.awt.BorderLayout.SOUTH);


		//pack();
	}//GEN-END:initComponents

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
		setVisible(false);
		dispose();
	}//GEN-LAST:event_closeDialog

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		//new ConfigQueryParamsDialog(new javax.swing.JFrame(), true).show();
	}

	private void addParams() {
		
		TelosObject genericQClass = m_obi.getIndividual("GenericQueryClass");
		Attribute param = m_obi.getAttribute(genericQClass, "parameter");
		ITelosObjectSet m_tos = m_obi.getAttributesOfCategory(m_telosQuery, param);

		Enumeration enTos = m_tos.sortedElements();
		
		java.util.logging.Logger.getLogger("global").fine("ConfigQueryParamsDialog.addParams:");
		JPanel newParam = null;
		m_paramPanel.setLayout(new BoxLayout(m_paramPanel, BoxLayout.Y_AXIS) );
		while(enTos.hasMoreElements() ){
			param = (Attribute)enTos.nextElement();
			java.util.logging.Logger.getLogger("global").fine("\t"+param+" destination: "+ param.getDestination());
			newParam = new JPanel();
			newParam.add(new JLabel(param.getLabel() +" ("+ param.getDestination()+")") );
			newParam.add(new JTextField(20) );
			m_paramPanel.add(newParam);
		}
		java.util.logging.Logger.getLogger("global").fine("end of paramlist");
	}

		// Variables declaration - do not modify//GEN-BEGIN:variables
		private javax.swing.JPanel m_paramContainer;
		private javax.swing.JButton jButton1;
		private javax.swing.JPanel m_buttonPanel;
		private javax.swing.JScrollPane jScrollPane1;
		private javax.swing.JPanel m_paramPanel;
		// End of variables declaration//GEN-END:variables

	}
