/*
The ConceptBase.cc Copyright

Copyright 1987-2025 The ConceptBase Team. All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice, this list of
      conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice, this list of
      conditions and the following disclaimer in the documentation and/or other materials
      provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE CONCEPTBASE TEAM ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE CONCEPTBASE TEAM OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those of the authors
and should not be interpreted as representing official policies, either expressed or implied,
of the ConceptBase Team.


The ConceptBase Team is represented by

Manfred Jeusfeld, University of Skovde, 54128 Skovde, Sweden


This license is a FreeBSD-style copyright license.
Legal home of the FreeBSD copyright license: http://www.freebsd.org/copyright/freebsd-license.html
*/
/*
 * SubmitQueryDialog.java
 *
 * Created on September 4, 2002, 5:08 PM
 */

package i5.cb.graph.cbeditor.components;

import i5.cb.CBConfiguration;
import i5.cb.graph.cbeditor.*;

/**
 *
 * @author  schoeneb
 */
public class SubmitQueryDialog extends javax.swing.JDialog {

    /** Creates new form SubmitQueryDialog */
    public SubmitQueryDialog(CBEditor cbEditor) {
        super( (java.awt.Frame)cbEditor, true);
        m_cbFrame = (CBFrame)cbEditor.getActiveGraphInternalFrame();
        initComponents();

        String[] recentQueries = CBConfiguration.getRecentQueries(m_cbFrame.getHost(), m_cbFrame.getPort());
        if(recentQueries.length != 0){
            actionButton.setEnabled(true);
            for(int i=0; i<recentQueries.length; i++){
                queryBox.addItem(recentQueries[i]);
            }
            queryBox.setSelectedIndex(0);
        }
        lResults.setModel(new javax.swing.DefaultListModel() );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        queryStringPanel = new javax.swing.JPanel();
        queryStringLabel = new javax.swing.JLabel();
        queryBox = new javax.swing.JComboBox();
        resultPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lResults = new javax.swing.JList(m_listModel);
        buttonPanel = new javax.swing.JPanel();
        newSearchButton = new javax.swing.JButton();
        actionButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setTitle(m_cbFrame.getBundle().getString("SubmitQueryDialog_Title"));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        queryStringPanel.setLayout(new java.awt.BorderLayout());

        queryStringPanel.setBorder(new javax.swing.border.EtchedBorder());
        queryStringLabel.setText(m_cbFrame.getBundle().getString("SubmitQueryDialog_queryStringLabel") + ":");
        queryStringPanel.add(queryStringLabel, java.awt.BorderLayout.WEST);

        queryBox.setEditable(true);
        queryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryBoxActionPerformed(evt);
            }
        });

        queryBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                queryBoxKeyTyped(evt);
            }
        });

        queryStringPanel.add(queryBox, java.awt.BorderLayout.CENTER);

        getContentPane().add(queryStringPanel, java.awt.BorderLayout.NORTH);

        resultPanel.setLayout(new java.awt.BorderLayout());

        lResults.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lResultsValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(lResults);

        resultPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(resultPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setBorder(new javax.swing.border.EtchedBorder());
        newSearchButton.setText(m_cbFrame.getBundle().getString("SubmitQueryDialog_newSearchButton"));
        newSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSearchButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(newSearchButton);

        actionButton.setText(m_cbFrame.getBundle().getString("SubmitQueryDialog_SubmitButton"));
        actionButton.setEnabled(false);
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(actionButton);

        cancelButton.setText(m_cbFrame.getBundle().getString("SubmitQueryDialog_CancelButton"));
        cancelButton.setToolTipText("null");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(408, 300));
        setLocation((screenSize.width-408)/2,(screenSize.height-300)/2);
    }//GEN-END:initComponents

    private void newSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSearchButtonActionPerformed
        lResults.setListData(new java.util.Vector() );
        actionButton.setText(m_cbFrame.getBundle().getString("SubmitQueryDialog_SubmitButton"));
        actionButton.removeActionListener(showAL);
        actionButton.addActionListener(submitAL);
    }//GEN-LAST:event_newSearchButtonActionPerformed

    private void queryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryBoxActionPerformed
        /*
        if( m_sCurrentQuery.equals( (String)queryBox.getSelectedItem()) ) return;

        m_sCurrentQuery = (String)queryBox.getSelectedItem();
        actionButton.setText(m_cbFrame.getBundle().getString("SubmitQueryDialog_SubmitButton"));
        actionButton.removeActionListener(showAL);
        actionButton.addActionListener(submitAL);
         */
        actionButton.setEnabled(true);
    }//GEN-LAST:event_queryBoxActionPerformed

    private void queryBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queryBoxKeyTyped
        /*
        if( m_sCurrentQuery.equals( (String)queryBox.getSelectedItem()) ) return;

        m_sCurrentQuery = (String)queryBox.getSelectedItem();
        actionButton.setText(m_cbFrame.getBundle().getString("SubmitQueryDialog_SubmitButton"));
        actionButton.removeActionListener(showAL);
        actionButton.addActionListener(submitAL);
         */
        actionButton.setEnabled(true);
    }//GEN-LAST:event_queryBoxKeyTyped

    private void lResultsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lResultsValueChanged
        actionButton.setEnabled(true);
    }//GEN-LAST:event_lResultsValueChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String sQuery = (String)queryBox.getSelectedItem();

        CBConfiguration.addRecentQuery(sQuery, m_cbFrame.getHost(), m_cbFrame.getPort() );

        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR) );
        java.util.Collection cResult = new CBQuery(sQuery , m_cbFrame).ask();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR) );

        if(cResult.size() == 0){
            String sNoObjs = m_cbFrame.getBundle().getString("SubmitQueryDialog_NoItemsFound");
            String[] a = { sNoObjs };
            lResults.setListData( a );
        }else{
            lResults.setListData(cResult.toArray() );
            actionButton.setText(m_cbFrame.getBundle().getString("SubmitQueryDialog_ShowButton") );
            actionButton.setEnabled(false);
            actionButton.addActionListener(showAL);
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Object[] cbUserObjs = lResults.getSelectedValues();
        for(int i=0; i<cbUserObjs.length; i++){
            CBUtil.createAndAddNewDiagramObject( (CBUserObject)cbUserObjs[i], m_cbFrame, null);
        }
    }

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel queryStringLabel;
    private javax.swing.JList lResults;
    private javax.swing.JComboBox queryBox;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel queryStringPanel;
    private javax.swing.JButton newSearchButton;
    private javax.swing.JPanel buttonPanel;
    // End of variables declaration//GEN-END:variables

    private CBFrame m_cbFrame;

    private SubmitActionListener submitAL = new SubmitActionListener();
    private ShowActionListener showAL = new ShowActionListener();

    private javax.swing.DefaultListModel m_listModel = new javax.swing.DefaultListModel();

    class SubmitActionListener implements java.awt.event.ActionListener{

        public void actionPerformed(java.awt.event.ActionEvent evt){
            submitButtonActionPerformed(evt);
        }
    }

    class ShowActionListener implements java.awt.event.ActionListener{

        public void actionPerformed(java.awt.event.ActionEvent evt){
            showButtonActionPerformed(evt);
        }
    }
}
