/* Generated By:JavaCC: Do not edit this line. TelosParserConstants.java */
package i5.cb.telos.frame;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TelosParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IN = 9;
  /** RegularExpression Id. */
  int ISA = 10;
  /** RegularExpression Id. */
  int WITH = 11;
  /** RegularExpression Id. */
  int END = 12;
  /** RegularExpression Id. */
  int END_PT = 13;
  /** RegularExpression Id. */
  int IN_CML = 14;
  /** RegularExpression Id. */
  int ISA_CML = 15;
  /** RegularExpression Id. */
  int WITH_CML = 16;
  /** RegularExpression Id. */
  int END_CML = 17;
  /** RegularExpression Id. */
  int SELECTOR1 = 18;
  /** RegularExpression Id. */
  int SELECTOR2 = 19;
  /** RegularExpression Id. */
  int SELECTORB = 20;
  /** RegularExpression Id. */
  int SCOPERES = 21;
  /** RegularExpression Id. */
  int ALPHANUM = 30;
  /** RegularExpression Id. */
  int Num = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;
  /** RegularExpression Id. */
  int LABEL = 33;
  /** RegularExpression Id. */
  int STRINGLABEL = 41;
  /** RegularExpression Id. */
  int RULELABEL = 43;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int PT = 1;
  /** Lexical state. */
  int CML = 2;
  /** Lexical state. */
  int WithinComment = 3;
  /** Lexical state. */
  int WithinString = 4;
  /** Lexical state. */
  int WithinRule = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"{$set syntax=PlainAachen}\"",
    "\"{$set syntax=PlainToronto}\"",
    "\"{$set syntax=CML}\"",
    "\"in\"",
    "\"isA\"",
    "\"with\"",
    "\"end\"",
    "\"end\"",
    "\"IN\"",
    "\"ISA\"",
    "\"WITH\"",
    "\"END\"",
    "<SELECTOR1>",
    "<SELECTOR2>",
    "<SELECTORB>",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"/\"",
    "<ALPHANUM>",
    "<Num>",
    "<NUMBER>",
    "<LABEL>",
    "\"\\\"\"",
    "\"$\"",
    "\"}\"",
    "<token of kind 37>",
    "<token of kind 38>",
    "\"\\\\\\\"\"",
    "\"\\\\\\\\\"",
    "\"\\\"\"",
    "<token of kind 42>",
    "\"$\"",
  };

}
