#!/bin/sh

DEFAULT_CB_HOME=`dirname $0`
RPATH=`realpath $DEFAULT_CB_HOME`
BNAME=`basename $RPATH`

if [ "$BNAME" = "ProductPOOL" ]; then
  DEFAULT_CB_HOME=$HOME/conceptbase
fi

CB_HOME=${CB_HOME:=$DEFAULT_CB_HOME}
export CB_HOME


# default java
JAVAEXEC=java


# We prefer to use one of the following javas; the last one is most preferred

# take /usr/bin/java if installed (standard location under Linux)
if [ -x /usr/bin/java ]; then
  JAVAEXEC=/usr/bin/java
fi

if [ "$1" ]; then
  exec $JAVAEXEC -Djava.awt.headless=false -DCB_HOME="$CB_HOME" -classpath "$CB_HOME/lib/classes/*" i5.cb.graph.cbeditor.CBEditor "$@"
else
# start with ohome.gel as argument to let cbgraph connect to a CBserver
  exec $JAVAEXEC -Djava.awt.headless=false -DCB_HOME="$CB_HOME" -classpath "$CB_HOME/lib/classes/*" i5.cb.graph.cbeditor.CBEditor "$CB_HOME/lib/ohome.gel"
fi



