%
% The ConceptBase.cc Copyright
%
% Copyright 1987-2020 The ConceptBase Team. All rights reserved.
%
% Redistribution and use in source and binary forms, with or without modification, are permitted
% provided that the following conditions are met:
%
%    1. Redistributions of source code must retain the above copyright notice, this list of
%       conditions and the following disclaimer.
%    2. Redistributions in binary form must reproduce the above copyright notice, this list of
%       conditions and the following disclaimer in the documentation and/or other materials
%       provided with the distribution.
%
% THIS SOFTWARE IS PROVIDED BY THE CONCEPTBASE TEAM ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
% INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
% PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE CONCEPTBASE TEAM OR CONTRIBUTORS BE
% LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
% (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
% OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
% CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
% OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
%
% The views and conclusions contained in the software and documentation are those of the authors
% and should not be interpreted as representing official policies, either expressed or implied,
% of the ConceptBase Team.
%
%
% The ConceptBase Team is represented by
%
% Manfred Jeusfeld, University of Skovde, 54128 Skovde, Sweden
% Matthias Jarke, RWTH Aachen, Informatik 5, Ahornstr. 55, 52056 Aachen, Germany
% Christoph Quix, RWTH Aachen, Informatik 5, Ahornstr. 55, 52056 Aachen, Germany
%
%
% This license is a FreeBSD-style copyright license.
% Legal home of the FreeBSD copyright license: http://www.freebsd.org/copyright/freebsd-license.html
%
%
%
% File:         %M%
% Version:      %I%
%
% Last Change:  05-Dec-1996 LWEB  (RWTH)
%
% Date released : %E%  (YY/MM/DD)
%
% SCCS-Source-Pool : %P%
% Date retrieved : %D% (YY/MM/DD)
% *************************************************************************
%
% This module is part of the BDMIntegrityChecker and
% is responsible for the compilation of new integrity constraints and rules.
%
%
%
% Exported predicates:
% --------------------
%
%   + NewIntegrityConstraint/3
%       When a new integrity constraint is added to the system (TELL),
%       it is translated here. This includes
%         - identifying the classes whose instances are affected by the integrity
%           constraint,
%         - creating simplified formulas and evaluable forms of them,
%         - inspecting and possibly translating rules that
%           generate objects that the integrity constraint may affect directly or
%           indirectly,
%         - storing the created formulas in internal predicates,
%         - creating the structure according to the model
%           (cf. CompleteBDMRuleConstraintModel.sml).
%
%   + NewRule/4
%       When a new rule is inserted into the system, it is here
%       translated, analogous to above. This includes
%         - recognizing the classes whose instances may be affected by the rule,
%       If objects that are generated by these rules enter an integrity
%       constraint (directly or indirectly):
%         - creating simplified formulas and evaluable forms thereof,
%         - viewing and possibly translating rules that
%           generate objects that may be directly or indirectly affected by this
%           rule through the integrity constraint,
%       And:
%         - storing the created formulas in internal predicates,
%         - creating the structure according to the model
%           (cf. CompleteBDMRuleConstraintModel.sml).
%
%
% 4-Jul-1990/MJf:
%   . triggers applyConstraintIfInsert, applyConstraintIfDelete,
%     applyRuleIfInsert, applyRuleIfDelete and deducedBy are now attributes
%     of PROPOSITION instead of CLASS
%
% 25.07.1990 RG:	Replaced STORE(propval...) by STORE(proposition...).
%
% 10-Aug-1992 MSt:     specialized forms in props represented by atoms(!)
% 			     surrounded by $
%
% 08-Jun-93/kvt bugfix cf. ErrorsCorrected[11]
% 06-Jul-93/kvt Encapsulation of triggers in BDMKBMS.pro
% 26-May-95/LWEB Integrity constraints extended by one slot storing the proposition
% 		ID so evaluation can check module visibility of the IC
%
% metaformula change (10.1.96)
% new predicate NewProcTrigger
%
%

:- module('BDMCompile',[
'NewIntegrityConstraint'/3
,'NewProcTrigger'/1
,'NewRule'/3
]).
:- use_module('GlobalPredicates.swi.pl').
:- use_module('debug.swi.pl').
:- use_module('FragmentToPropositions.swi.pl').
:- use_module('PropositionProcessor.swi.pl').
:- use_module('validProposition.swi.pl').
:- use_module('GeneralUtilities.swi.pl').
:- use_module('ErrorMessages.swi.pl').
:- use_module('Literals.swi.pl').
:- use_module('BDMTransFormula.swi.pl').
:- use_module('BDMLiteralDeps.swi.pl').
:- use_module('BDMKBMS.swi.pl').
:- use_module('MSFOLassertionUtilities.swi.pl').
:- use_module('PrologCompatibility.swi.pl').
:- use_module('GlobalParameters.swi.pl').
:- style_check(-singleton).
%  ====================
%  Exported predicates:
%  ====================
%  ***************************************************************************
%
%  NewIntegrityConstraint( _ranges, _rangeform, _IcId)
%
%  This predicate processes a new integrity condition. Provided
%  is that an object (with the identifier _IcId) has already been created,
%  which represents the integrity condition.
%  Procedure:
%        - Storing the entire integrity constraint.
% 	- Processing the formula: with each literal of the formula
% 	  (insofar as it touches the database):
% 	  - Identifying the classes whose instances may be represented by this literal
% 	    and
% 	  - Creating the so-called simplified instance of the integrity
% 	    condition with respect to this literal.
% 	  - Searching for and processing a rule that generates objects that may be
%            affected by this literal.
% 	  - Storing the found information.
%
%  _ranges    : specifications about the occurring variables
%  _rangeform : the formula of the new integrity constraint; for the exact
% 	       format see elsewhere, (i)
%  _IcId      : identifier of the object that represents the integrity
%               condition (i)
%
%  ***************************************************************************

'NewIntegrityConstraint'( _ranges, _rangeform, _IcId) :-
	'VarsOfRangeform'(_rangeform,_vars),
	convert(_rangeform,_rangeformO),  % kvt
	'RangeToEvaForm'(_vars,_ranges,_rangeformO, 'TRUE',_evaform, _),
	store_origConstraint(_evaform, _IcId),
	generateSpecializations(_vars,_ranges,_rangeformO,_IcId),
	!,
	'error_number@F2P'(0).  % Compilation must have been successful!
generateSpecializations(_vars,_ranges, _rangeform, _IcId) :-
  'PassThruRangeform'(_rangeform,
	  'ExamIcLiterals'(_ranges, _rangeform, _IcId, _vars)),
  !.
%  ***************************************************************************
%
%  NewRule(_ranges, _rangeform, _RuleId)
%
%  When a new rule is introduced, it is processed with this predicate
%  etc. It is assumed that it is already stored as an object
%  stored. Depending on the type of literals and the degree of
%  instantiation, the classes are determined whose instances may be affected by this
%  literal, as well as additional restriction tests (analogous to the
%  procedure for a new integrity constraint).
%  If the objects generated by this rule enter an integrity test,
%  then additional references to those affected by the condition literals are combined
%  these objects (or their classes) are created.
%
%  _rangeform : deductive rule in the form rangerule(_cond,_concl) (i)
%  _concl_lit : conclusion part of the rule; this is a single literal, (i)
%  _RuleId     : the identifier of the object representing the rule (i)
%
%  ***************************************************************************

'NewRule'(_ranges, rangerule(_rangecond,_rangeconcl), _RuleId) :-
	'VarsOfRangeform'(_rangecond,_vars),
	%  1. Storing the complete rule:
	%
	%  1a. For this it must be determined from which class the rule can derive instances:
	%

	'ConcernedClass'(_vars,_ranges,_rangeconcl,_class),
	'AdmissableConclusionClass'(_class),
	convert(_rangecond,_rangecondO),
	'RangeToEvaForm'(_vars,_ranges, rangerule(_rangecondO,_rangeconcl),'TRUE', evarule(_evaform_cond,_evaform_concl),_),
	%  1c. And now the ... are complete rule, in internal formats, and the affected class stored:
	%

	  store_origRule(_evaform_cond, _evaform_concl, _RuleId, _class, ruleinfo(_rangecondO,_rangeconcl,_ranges,_vars)),
	%  2. Compiling the rule:
	%
	%  2a. Compiling the rule w.r.t. insert operations:
	%
	%  Check whether from the class whose instances may be affected by the rule-head literal, references regarding integrity constraints or rules emanate that would have to be tested during an insert operation:
	%

	findall( _SimpIcIdIns,
		   (
			retrieve_BDMFormula( 'applyConstraintIfInsert@BDMCompile'( _icID, _class, _SimpIcIdIns, _, _)),
			retrieve_proposition('P'(_icID,_,_,_))  % 26-May-1995 LWEB
		   ),
		_ListOfSimpIcIdsInsert),
 	findall( _SimpRuleIdIns,
		retrieve_BDMFormula('applyRuleIfInsert@BDMCompile'( _RuleId, _class, _SimpRuleIdIns, _, _, _, _)),
		_ListOfSimpRuleIdsInsert),
	%  And compile the found formulas:
	%

	((_ListOfSimpIcIdsInsert = [],
	  _ListOfSimpRuleIdsInsert = []
	 );
	 'PassThruRangeform'( _rangecondO, 'ExamCondLitsForRuleOrIc'('Insert', _ranges, _rangecondO, _rangeconcl, _RuleId, _ListOfSimpIcIdsInsert, _ListOfSimpRuleIdsInsert, _vars))),
	%  2b. With respect to delete operations:
	%
	%  Check whether references concerning integrity constraints or rules that would need to be tested during a delete operation emanate from the class whose instances could be affected by the rule-head literal:
	%

	findall( _SimpIcIdDel,
		(
			retrieve_BDMFormula('applyConstraintIfDelete@BDMCompile'( _IcId, _class, _SimpIcIdDel, _, _)),
			retrieve_proposition('P'(_IcId, _, _, _))  % 26-May-1995 LWEB
		),
		_ListOfSimpIcIdsDelete),
	findall( _SimpRuleIdDel,
		retrieve_BDMFormula('applyRuleIfDelete@BDMCompile'( _RuleId, _class, _SimpRuleIdDel, _, _, _, _)),
		_ListOfSimpRuleIdsDelete),
	%  And compile the found formulas:
	%

 	((_ListOfSimpIcIdsDelete = [],
	  _ListOfSimpRuleIdsDelete = []
	 );
	 'PassThruRangeform'( _rangecondO, 'ExamCondLitsForRuleOrIc'( 'Delete', _ranges, _rangecondO, _rangeconcl, _RuleId, _ListOfSimpIcIdsDelete, _ListOfSimpRuleIdsDelete, _vars))),
	!,
	%  Compilation must have been successful!
	%

	'error_number@F2P'(0).
%  16-Jul-1991/MJf: error handling
%

'NewRule'(_ranges, rangerule(_rangecond,_rangeconcl), _RuleId) :-
	increment('error_number@F2P'),
	report_error('NORULE', 'BDMCompile', [objectName(_RuleId)]),
	!,
	fail.
% *************************************************************************
%
%  NewProcTrigger(_trig)
%
%  Trigger _trig has the functor applyPredicateIfInsert or applyPredicateIfDelete
%  and is then passed directly to BDMKBMS for maintenance of the simplified
%  formulas generated from metaformulas
% *************************************************************************

'NewProcTrigger'(_trig) :-
	store_BDMFormula(_trig).
%  ===================
%  Private predicates:
%  ===================
%  ===========================================================================
%  *************** predicates that serve only for new ICs: *****************
%  =========================================================================
%  **************************************************************************
%
%  ExamIcLiterals(_sign,_lit,_ranges,_rangeform,_IcId,_vars)
%
%  Here the integrity constraint formula with respect to a certain
%  of its literals is processed, i.e.
% 	1. Recognizing the affected class
% 	2. Creating the simplified instance of the integrity constraint
% 	3. Check whether rules must be observed
% 	4. Storing the found information.
%
%  _sign: sign of the literal (i)
%  _lit       : The literal with respect to which the integrity constraint is processed, (i)
%  _ranges    : table mapping variables to their "ranges" (classes) (i)
%  _rangeform : the formula of the integrity constraint that is processed w.r.t. the literal
%               is to be processed, (i)
%  _IcId      : the identifier of the object that represents the integrity constraint
%               represents, (i)
%  _vars      : information about the variables of the formula: vars(_a,_b)  (i)
%                _a = all variables
%                _b = all universally quantified variables that do not lie in the
%                     scope of an existential quantifier.
%
%  **************************************************************************
%  If _lit is a 'weak literal' (comparison operators, instances of
%  functions such as COUNT), then no 'simplified rangeforms' are
%  generated, because changes to the extension of this literal cannot
%  (so easily) be determined incrementally.

'ExamIcLiterals'(_sign, _lit, _ranges, _rangeform, _IcId, _vars) :-
  'WeakLiteral'(_lit),
  !.
'ExamIcLiterals'(_sign, _lit, _ranges, _rangeform, _IcId, _vars) :-
  'ConcernedClass'(_vars, _ranges, _lit, _class),
  'ExamIcLiteralsCC'(_sign, _lit, _class, _ranges, _rangeform, _IcId, _vars),
  !.

'ExamIcLiteralsCC'(_sign, _lit, _class, _ranges, _rangeform, _IcId, _vars) :-
  noTriggerLiteral(_class,_lit),
  !.
% 3-Jun-2004/M.Jeusfeld: check for forbidden orccurences of query classes
%  Only when a query class _class is also an instance of MSFOLrule, it can
%  be referred to in a constraint (or rule). Reason: a query class needs to
%  be an instance of MSFOLrule to instruct ConceptBase to generate the
%  triggers necessary for integrity checking.

'ExamIcLiteralsCC'(_sign, _lit, _class, _ranges, _rangeform, _IcId, _vars) :-
  prove_edb_literal('In_e'(_class,id_65)),  % id_65=QueryClass
  not_prove_literal('In'(_class,id_46)),  % id_46=MSFOLrule
  !,
  increment('error_number@F2P'),
  report_error('QUERYCLASS_NOT_IN_IC', 'BDMCompile', [objectName(_class),constraint,objectName(_IcId)]),
  !,
  fail.
%  29-Nov-2005/M.Jeusfeld: generic query classes may not occur in constraints (or rules)
%  since the incremental constraint evaluator cannot handle them correctly. See also
%  ticket #16 and #90.
%  31-Aug-2006/M.Jeusfeld: this is only enforced when CBserver parameter -cc
%  (forceConcernedClass) is not set to off. Novice users are encouraged to use strict
%  as it guarantees a more correct and stable behavior at the expense of flexibility.

'ExamIcLiteralsCC'(_sign, _lit, _class, _ranges, _rangeform, _IcId, _vars) :-
  get_cb_feature(forceConcernedClass,_ccmode),
  _ccmode \= off,
  prove_literal('In'(_class,id_72)),  % id_72=GenericQueryClass
  !,
  increment('error_number@F2P'),
  report_error('GENERIC_QUERYCLASS_NOT_IN_IC', 'BDMCompile', [objectName(_class),constraint,objectName(_IcId)]),
  !,
  fail.
'ExamIcLiteralsCC'(_sign, _lit, _class, _ranges, _rangeform,
               _IcId, _vars) :-
  effectiveInsDel(_sign,'Insert',_InsDel),
  'SimplifyRangeform'(_ranges,_rangeform,_InsDel,_lit,_vars,
                    _simplifiedrangeform),
  'RangeToEvaForm'(_vars,_ranges,_simplifiedrangeform,_lit,
                 _simplifiedevaform,_InstLiteral),
  constructStoredForm(_simplifiedrangeform,_ranges,_InsDel,_lit,_InstLiteral,_StoredForm),
  store_applyConstraint(_InsDel,_simplifiedevaform,_IcId,
                        _InstLiteral,_class,_SimpIcId,_StoredForm),
        %  Check whether a rule generated objects that could be affected by the
	%  literal. If so, all classes whose instances appear in condition literals
	%  of this rule must receive a special reference.

  'RuleConcernsThisClass'(_class, toldIC(_SimpIcId), _InsDel),
  !.
%  16-Jul-1991/MJf: error handling

'ExamIcLiteralsCC'(_sign, _lit, _class, _ranges, _rangeform, _IcId, _vars) :-
   increment('error_number@F2P'),
   report_error('NOSPEC', 'BDMCompile', [objectName(_IcId),formula(_lit)]),
   !,
   fail.
%  **************************************************************************
%
%  SimplifyRangeform( _ranges, _rangeform, _InsDel,_lit, _vars,
%                     _simplifiedrangeform)
%
%  _ranges      : table of occurring variables with their "ranges" (i)
%  _rangeform   : the integrity constraint (i) to be simplified,
%  _InsDel      : indicator whether the simplified IC is to be tested during
%                 an insert or delete operation (i).
%  _lit         : with respect to which the IC is to be simplified (i),
%  _vars        : variables of the formula, cf. ExamIcLiterals (i),
%  _simplifiedrangeform : the simplified integrity constraint (o),
%
%  Here the specified integrity constraint is simplified with respect to one
%  of its literals.
%
%  **************************************************************************

'SimplifyRangeform'(_ranges, _rangeform, _InsDel, _lit, _vars,
                  _simplifiedrangeform) :-
	_lit =.. [ _LiteralName | _LiteralArgs],
		%  1. Eliminate variables that appear as arguments of the
		%     literal and are universally quantified but do not lie in the
		%     scope of an existential quantifier:

	'ElimQuantsInRangeform'(_ranges,_LiteralArgs,_vars,_rangeform,
		              _rangeform_woquants,_all_elimed),
		%  2. Under certain circumstances omit the literal from
		%     the formula and simplify it:

        'InsertOrDelete'(_all_elimed, _InsDel, _lit, _rangeform_woquants,
                       _simplifiedrangeform),
'WriteTrace'(veryhigh,'BDMCompile',
           [idterm('SimplifyRangeform'(_InsDel,_lit)),'--->',idterm(_simplifiedrangeform)]),
	!.
%  **************************************************************************
%
%  ElimQuantsInRangeform( _ranges,_LiteralArgs,_vars,_rangeform,
%                         _rangeform_woquants, _all_elimed)
%
%  Delete quantifications of those variables that occur in the arguments
%  of a literal, are universally quantified, but do not lie in the scope of
%  an existential quantifier.
%
%  _ranges      : table of occurring variables with their "ranges" (i)
%  _LiteralArgs       : the arguments of a literal (i),
%  _vars         : cf. ExamIcLiterals (i),
%  _rangeform         : formula to search, (i)
%  _rangeform_woquants: the same formula but without the quantification of the
%                       variables that are arguments of the literal and
%                       are also listed in vars(_,_b), (o)
%  _all_elimed        : indicates whether all quantifications of variables
%                       occurring in the arguments of the literal could be
%                       deleted (yes) or not (no). (o)
%
%  **************************************************************************
%  Done, nothing more to do.

'ElimQuantsInRangeform'(_ranges, [], _, _rangeform, _rangeform, yes) :- !.
%  The first (current) argument is a variable that is also listed in
%  _AllquVars (i.e. the variable is universally quantified in the formula
%  and no existential quantifier appears before it). Therefore the
%  quantification of the variable is removed from the formula.

'ElimQuantsInRangeform'(_ranges, [ _arg | _args_rest], vars(_a,_b),
                      _rangeform, _rangeform_woquants, _all_elimed) :-
	member( _arg, _b),
	!,
	'ElimQuant'( _arg, _rangeform, _rangeform_woquant),
	'ElimQuantsInRangeform'(_ranges,_args_rest, vars(_a,_b),
                              _rangeform_woquant,
	                      _rangeform_woquants, _all_elimed).
%  The current argument is indeed a variable, but it does not appear
%  in vars(_,_b), i.e. nothing to do here, continue.
%  In particular, _all_elimed = no!

'ElimQuantsInRangeform'(_ranges, [ _arg | _args_rest], vars(_a,_b),
                      _rangeform, _rangeform_woquants, no) :-
	member(_arg,_a),
	!,
	'ElimQuantsInRangeform'(_ranges, _args_rest, vars(_a,_b), _rangeform,
                              _rangeform_woquants, _).
%  The first (current) argument is a constant;
%  nothing to do here, continue.

'ElimQuantsInRangeform'(_ranges, [_arg|_args_rest], _vars,
                      _rangeform, _rangeform_woquants, _all_elimed) :-
	!,
	'ElimQuantsInRangeform'(_ranges, _args_rest, _vars, _rangeform,
                              _rangeform_woquants, _all_elimed).
%  **************************************************************************
%
%  InsertOrDelete( _all_elimed, _InsDel, _lit, _rangeformWoQuants,
%                             _rangeformWoLit)
%
%  Here is finally the so-called simplified instance of an IC
%  created with respect to one of its literals. The quantifications
%  of variables occurring in this literal were, where permitted,
%  already deleted previously.
%
%  _all_elimed        : indicates whether the quantifications of all variables
%                       occurring in the literal were deleted (yes) or not (no), (i)
%  _InsDel            : indicates whether _rangeformWoQuants is to be specialized
%                       with respect to insertion ('Insert') or deletion ('Delete')
%                       of _lit, (i)
%  _lit               : the literal from the formula with respect to which the so-called
%                       simplified instance of the formula is built, (i)
%  _rangeformWoQuants : the formula in which the required deletions of
%                       quantifications were performed, (i)
%  _rangeformWoLit    : if _all_elimed=yes and _InsDel=Insert, then
%                       negated occurrences of _lit in _rangeformWoQuants
%                       are replaced by FALSE or eliminated (o)
%
%  **************************************************************************
%  If not all variables of the inspected literal _lit were
%  eliminated, then _rangeform cannot be simplified further:

'InsertOrDelete'(no, 'Delete', _lit, _rangeform, _rangeform) :- !.
'InsertOrDelete'(no, 'Insert', _lit, _rangeform, _rangeform) :- !.
%  For 'Delete' no literal can disappear:

'InsertOrDelete'(yes, 'Delete', _lit, _rangeform, _rangeform) :- !.
%  negative _lit occurs in the (implicitly negative) literals
%  behind a 'forall': replace it by FALSE, i.e.
%  simply delete it from the list
%  ### Assumption: _lit occurs at most once in _lits; this
%  is reasonable since x and x = x or x = x

'InsertOrDelete'(yes, 'Insert', _lit,
               forall(_vars,_lits,_rangeF),
               forall(_vars,_newlits,_rangeF)) :-
   member(_lit,_lits),
   delete(_lit,_lits,_newlits),
   !.
%  search in an inner 'forall':

'InsertOrDelete'(yes, 'Insert', _lit,
               forall(_vars,_lits,_rangeF),
               forall(_vars,_lits,_rangeFwoLit)) :-
  !,
  'InsertOrDelete'(yes, 'Insert',_lit,_rangeF,_rangeFwoLit).
%  Search in conjunctions and disjunctions:

'InsertOrDelete'(yes, 'Insert', _lit,
               and(_rF1,_rF2),
               and(_newrF1,_newrF2)) :-
   'InsertOrDelete'(yes, 'Insert', _lit, _rF1, _newrF1),
   'InsertOrDelete'(yes, 'Insert', _lit, _rF2, _newrF2),
   !.
'InsertOrDelete'(yes, 'Insert', _lit,
               or(_rF1,_rF2),
               or(_newrF1,_newrF2)) :-
   'InsertOrDelete'(yes, 'Insert', _lit, _rF1, _newrF1),
   'InsertOrDelete'(yes, 'Insert', _lit, _rF2, _newrF2),
   !.
%  individually occurring negative literal
%  it is replaced by FALSE on 'Insert'

'InsertOrDelete'(yes, 'Insert', _lit,
               not(_lit),
               'FALSE') :- !.
%  any positive literal (including TRUE, FALSE)
%  it cannot be replaced on 'Insert'

'InsertOrDelete'(yes, 'Insert', _lit, _somelit, _somelit) :- !.
%  ============================================================================
%  ***************** Predicates that process rules: **********************
%  ============================================================================
%  ***************************************************************************
%
%  ExamCondLitsForRuleOrIc( _sign,_Literal, _InsDelConcl ,
%                           _RuleCondFormula, _RuleConcl, _RuleId,
%                       _ListOfSimpIcIds, _ListOfSimpRuleIds, _InsDel,_vars)
%
%  Here each individual literal of a rule's condition formula is pro-
%  cessed: creating the simplified form of the rule, creating references to other
%  integrity constraints or rules, ...
%  The affected class and the simplified form of the rule are determined
%  and stored; finally this simplified form is used to create the
%  references to other simplified rules or integrity constraints
%  created that concern instances of the class affected by the conclusion literal of the
%  current rule. Finally it must be examined whether
%  whether instances of the class affected by the current literal of the current formula
%  affected class itself can be derived by a rule,
%  such a rule must then be processed using the same procedure.
%
%  _sign : sign of the Literals (i).
%  _lit               : The current literal of the condition formula of the current
%                       rule that is now to be processed, (i)
%  _RuleCondFormula   : the condition formula of the current rule, (i)
%  _RuleConcl         : the conclusion literal of the current rule, (i)
%  _RuleId            : the identifier of the object that represents the current
%                       rule, (i)
%  _ListOfSimpIcIds   : a list of identifiers of simplified forms
%                       of integrity constraints into which instances of the clas-
%                       se are involved in that are affected by the conclusion literal of the current-
%                       all rules are affected, (i)
%  _ListOfSimpRuleIds : same with simplified rules, (i)
%
%  ***************************************************************************
%  similar to ExamIcLiterals
%  Weak litarals are for example comparison literals

'ExamCondLitsForRuleOrIc'( _sign,_lit,_InsDelConcl, _ranges,
                         _rangecond, _rangeconcl, _RuleId,
                         _ListOfSimpIcIds, _ListOfSimpRuleIds,_vars) :-
  'WeakLiteral'(_lit),
  !.
'ExamCondLitsForRuleOrIc'( _sign,_lit,_InsDelConcl, _ranges,
                         _rangecond, _rangeconcl, _RuleId,
                         _ListOfSimpIcIds, _ListOfSimpRuleIds,_vars) :-
  'ConcernedClass'(_vars, _ranges, _lit, _class),  % only compute the concerned class once
  'ExamCondLitsForRuleOrIcCC'( _sign,_lit,_InsDelConcl, _class, _ranges,
                         _rangecond, _rangeconcl, _RuleId,
                         _ListOfSimpIcIds, _ListOfSimpRuleIds,_vars).

'ExamCondLitsForRuleOrIcCC'( _sign,_lit,_InsDelConcl, _class, _ranges,
                         _rangecond, _rangeconcl, _RuleId,
                         _ListOfSimpIcIds, _ListOfSimpRuleIds,_vars) :-
  prove_edb_literal('In_e'(_class,id_65)),  % id_65=QueryClass
  not_prove_literal('In'(_class,id_46)),  % id_46=MSFOLrule
  !,
  increment('error_number@F2P'),
  report_error('QUERYCLASS_NOT_IN_IC', 'BDMCompile', [objectName(_class),rule,objectName(_RuleId)]),
  !,
  fail.
%  same exclusion of GenericQueryClass as for ExamIcLiterals:

'ExamCondLitsForRuleOrIcCC'( _sign,_lit,_InsDelConcl, _class, _ranges,
                         _rangecond, _rangeconcl, _RuleId,
                         _ListOfSimpIcIds, _ListOfSimpRuleIds,_vars) :-
  prove_literal('In'(_class,id_72)),  % id_72=GenericQueryClass
  !,
  increment('error_number@F2P'),
  report_error('GENERIC_QUERYCLASS_NOT_IN_IC', 'BDMCompile', [objectName(_class),constraint,objectName(_IcId)]),
  !,
  fail.
%  the literal _lit with concerned class _class is a no trigger literal, e.g.
%  because _class is an immutable attribute

'ExamCondLitsForRuleOrIcCC'( _sign,_lit,_InsDelConcl, _class, _ranges,
                         _rangecond, _rangeconcl, _RuleId,
                         _ListOfSimpIcIds, _ListOfSimpRuleIds,_vars) :-
  noTriggerLiteral(_class,_lit),
  !.
'ExamCondLitsForRuleOrIcCC'( _sign,_lit,_InsDelConcl, _class, _ranges,
                         _rangecond, _rangeconcl, _RuleId,
                         _ListOfSimpIcIds, _ListOfSimpRuleIds,_vars) :-
   effectiveInsDel(_sign,_InsDelConcl,_effInsDel),
		%  Creating the simplified form of the rule:

   'SimplifyRangeform'(_ranges, _rangecond, _effInsDel, _lit, _vars,
                  _simplifiedrangecond),
   'RangeToEvaForm'(_vars,_ranges,rangerule(_simplifiedrangecond,_rangeconcl),
                  _lit, evarule(_evacond,_evaconcl),_InstLiteral),
		%  Store the information found:

   store_applyRule( _effInsDel,
                 _evacond, _evaconcl, _RuleId,
	         _InstLiteral, _class, _InsDelConcl,
	         _ListOfSimpIcIds, _ListOfSimpRuleIds, _SimpRuleId),
		%  Are instances of the affected class derived by a rule?

   'RuleConcernsThisClass'( _class, toldRule(_SimpRuleId), _effInsDel),
   !.
%  16-Jul-1991/MJf: error handling

'ExamCondLitsForRuleOrIcCC'( _sign,_lit,_InsDelConcl, _class, _ranges,
                         _rangecond, _rangeconcl, _RuleId,
                         _ListOfSimpIcIds, _ListOfSimpRuleIds,_vars) :-
   increment('error_number@F2P'),
   report_error('NOSPEC', 'BDMCompile', [objectName(_RuleId),formula(_lit)]),
   !,
   fail.
%  ***************************************************************************
%                                                             5-Nov-1990/MJf
%  effectiveInsDel( _sign, _InsDelOfConcl, _effInsDel)
%
%  This predicate computes from the sign of the literal occurrence (given
%  through _sign) and from the required operation on the inference
%  literals (_InsDelOfConcl) the resulting operation on the literal
%  occurrence:
%
%     _sign=negative (neg. literal occurrence)
%     _InsDelOfConcl=Insert (insert of conclusion literal is monitored)
%     ===>
%     _effInsDel=Insert (monitor insert of the literal occurrence!)
%
%     _sign=positive (pos. literal occurrence)
%     _InsDelOfConcl=Insert (insert of conclusion literal is monitored)
%     ===>
%     _effInsDel=Delete (monitor delete of the literal occurrence!)
%
%     _sign=negative (neg. literal occurrence)
%     _InsDelOfConcl=Delete (delete of conclusion literal is monitored)
%     ===>
%     _effInsDel=Delete (monitor delete of the literal occurrence!)
%
%     _sign=positive (pos. literal occurrence)
%     _InsDelOfConcl=Delete (delete of conclusion literal is monitored)
%     ===>
%     _effInsDel=Insert (monitor insert of the literal occurrence!)
%
%  Note: integrity constraints can be viewed as rules that
%  have TRUE as inference literal. Therefore _InsDelOfConcl=Insert must be
%  set!
%
%
%  ***************************************************************************

effectiveInsDel(negative,'Insert','Insert') :- !.
effectiveInsDel(positive,'Insert','Delete') :- !.
effectiveInsDel(negative,'Delete','Delete') :- !.
effectiveInsDel(positive,'Delete','Insert') :- !.
%  ***************************************************************************
%
%  RuleConcernsThisClass( _ClassId, _told, _InsDel)
%
%  Instances of the specified class enter the integrity test (in)directly.
%  If instances of the specified class are derived by a rule,
%  then the classes whose instances appear in this rule must
%  get a special reference to a simplified form of this rule;
%  from this simplified form, a reference to the rule or
%  integrity constraint is created into which the instances of the specified class
%  enter.
%
%  _ClassId : identifier of the class to be checked for rule dependency, (i)
%  _told    : contains the identifier of the simplified form for the _InsDel
%             operation (i)
%                toldIC(_SimpIcId) - _SimpIcId was newly generated for the
%                                    _InsDel operation on _ClassId
%                toldRule(_SimpRuleId) - analogous, however a rule was
%                                    generated
%  _InsDel  : indicator of whether _told is responsible for insert or delete
%             operations (i)
%
%  ***************************************************************************

'RuleConcernsThisClass'( _ClassId, _told, _InsDel):-
		%  1. Are instances of the affected class derived by a rule?

        prove_edb_literal(  'A_e'(_ClassId,'Proposition',deducedBy,_OrigRuleId) ),
        prove_edb_literal(  'A_e'(_RuleId,'MSFOLrule',originalRule,_OrigRuleId) ),
		%  Yes, namely through the rule with the identifier _RuleId.
		%  2. Process this rule:

	'RuleConcernsThisClass_help'( _OrigRuleId, _RuleId, _told, _InsDel),
		%  So that all rules that derive instances of the given class
		%  are considered:

	fail.
'RuleConcernsThisClass'( _, _, _):-
	!.

'RuleConcernsThisClass_help'( _OrigRuleId, _RuleId, _told, _InsDel) :-
        %  1. Determine all simplified forms of _RuleId

        findall(_simprule,
                prove_edb_literal('A_e'(_RuleId,'MSFOLrule',specialRule,_simprule)),
                _allsimprules),
        updateGoAheads(_allsimprules,_RuleId,_told,_InsDel,
                       _InsDel,_unsupported),
        recompileRule(_OrigRuleId,_RuleId,_told,_unsupported),
        !.
%   The rule was already compiled for the desired case:

recompileRule(_OrigRuleId,_RuleId,_told, nil) :-  !.
%  otherwise:

recompileRule(_OrigRuleId,_RuleId,_told,_InsDel) :-
		%  Get the formula of the rule:

	retrieve_BDMFormula(
              'origRule@BDMCompile'( _RuleId, _, _body,
                           ruleinfo(_rangecond,_rangeconcl,_ranges,_vars)) ),
		%  Process the formula, i.e. create the information for each
		%  individual literal of the formula:

        'WriteTrace'(high,'BDMCompile', ['Original rule with body ',idterm(_body),
                   ' has to be re-compiled for the case "', _InsDel,
                   '" of its conclusion literal ',idterm(_rangeconcl)]),
        newGoAheads(_told,_ListOfSimpIcIds,_ListOfSimpRuleIds),
        !,
	'PassThruRangeform'( _rangecond,
	   'ExamCondLitsForRuleOrIc'(_InsDel,_ranges,_rangecond,_rangeconcl,_RuleId,
	             _ListOfSimpIcIds,_ListOfSimpRuleIds,_vars)),
	!.

newGoAheads(  toldIC(_SimpIcId),      [_SimpIcId],  []             ).
newGoAheads(  toldRule(_SimpRuleId),  [],           [_SimpRuleId]  ).
%  When the rule (_RuleId) that derives instances of the class that enter a
%  new integrity constraint or rule has already been translated, only the
%  new additional information about what must be done after applying this rule
%  needs to be stored.
%  _unsupported indicates whether re-compilation of the rule is still required.
%  This case occurs when the rule has not yet been simplified for the operation
%  _InsDel on the conclusion literal.

updateGoAheads([],_RuleId,_told,_InsDel,
               _unsupported,_unsupported) :- !.
updateGoAheads([_SimpRuleId|_rest],_RuleId,_told,_InsDel,
               _tillNow,_unsupported) :-
        newGoAheads(_told,_ListOfSimpIcIds,_ListOfSimpRuleIds),
	store_more_applyConsRule(_InsDel,_SimpRuleId,_ListOfSimpIcIds,
		_ListOfSimpRuleIds),
        !,
        updateGoAheads(_rest,_RuleId,_told,_InsDel,
                       nil,_unsupported).
%  Note: store_more_applyConsRule causes a fail if _SimpRuleId
%  does not support _InsDel in its goAhead.

updateGoAheads([_|_rest],_RuleId,_told,_InsDel,
               _tillNow,_unsupported) :-
       updateGoAheads(_rest,_RuleId,_told,_InsDel,_tillNow,_unsupported).
%  ===========================================================================
%  ****** predicates that serve both for new ICs and also as rules: *******
%  ===========================================================================
%  20-Nov-2002/M.Jeusfeld: excludeDoublettes cares for the exclusion of double
%  occurrences of matchable literals _lit1,_lit2 in _lits in order not to
%  generate simplified forms for both _lit1 and _lit2.
%    Example:
%        forall([x1,x2,z],[P1(x1,m,x2),P2(x1,z),P1(x2,m,x1)],_f)
%  Heres, the two literals P1(x1,m,x2) and P1(x2,m,x1) are matching. We only
%  have to feed incremental updates (delete,insert) into one of the two
%  occurrences. Note: the second occurrence is excluded from having simplified
%  forms (triggers) generated for it. It does not mean that it is eliminated
%  from the formula as such.
%  Note: The directly quantified variables of _lit1 must the the same as those
%  of _lit2. Then, any trigger to the one literal fully instantiates the other
%  and vice versa.

excludeDoublettes(_vars,_lits,_newlits) :-
  removeDoublettes(_vars,_lits,_newlits),
  !.

removeDoublettes(_vars,[_lit|_restlits],_restnewlits) :-
  occursDoublette(_vars,_lit,_restlits),
  !,
  removeDoublettes(_vars,_restlits,_restnewlits).
removeDoublettes(_vars,[_lit|_restlits],[_lit|_restnewlits]) :-
  removeDoublettes(_vars,_restlits,_restnewlits).
removeDoublettes(_vars,[],[]).

occursDoublette(_vars,_lit1,[_lit2|_]) :-
  matchableLit(_vars,_lit1,_lit2),
  'WriteTrace'(veryhigh,'BDMCompile',
           ['The literal occurs ',idterm(_lit1), ' has doublette ',idterm(_lit2),' and does not require trigger generation']),
  !.
occursDoublette(_vars,_lit,[_|_rest]) :-
  occursDoublette(_vars,_lit,_rest).

matchableLit(_vars,_lit1,_lit2) :-
  _lit1 =.. [_pred|_args1],
  _lit2 =.. [_pred|_args2],
  sameSignature(_vars,_args1,_args2),
  !.

sameSignature(_allvars,_args1,_args2) :-
  checkSameSignature(_allvars,_args1,_args2,_args1,_args2).

checkSameSignature(_,_args1,_args2,[],[]).
checkSameSignature(_allvars,_args1,_args2,[_x|_rest1],[_y|_rest2]) :-
  matchingArgs(_allvars,_args1,_args2,_x,_y),
  checkSameSignature(_allvars,_args1,_args2,_rest1,_rest2).

matchingArgs(_allvars,_args1,_args2,_x,_x) :- !.
matchingArgs(_allvars,_args1,_args2,_x,_y) :-
  member(_x,_allvars),
  member(_y,_allvars),
  member(_x,_args2),  % this makes sure that _lit1 and _lit2 have
  member(_y,_args1),  % exactly the same vars
  !.
%  ***************************************************************************
%
%  PassThruRangeform( _rangeform, _Predicate)
%
%  This predicate merely traverses the formula, in order to then process the individual
%  literals to the processing step. The specific further processing
%  is determined by the given predicate.
%  The current literal to be processed is prepended to the arguments of this predicate.
%
%  _rangeform : The formula to be executed in sequence, (i)
%  _Predicate : the predicate to be executed for each individual literal of the
%               formula. (i)
%
%  ***************************************************************************

'PassThruRangeform'(forall(_vars,_lits,_rangeF),_GenericPred) :-
  excludeDoublettes(_vars,_lits,_newlits),
  'PassThruLits'(negative,_newlits,_GenericPred),
  'PassThruRangeform'(_rangeF,_GenericPred),
  !.
'PassThruRangeform'(exists(_vars,_lits,_rangeF),_GenericPred) :-
  excludeDoublettes(_vars,_lits,_newlits),
  'PassThruLits'(positive,_newlits,_GenericPred),
  'PassThruRangeform'(_rangeF,_GenericPred),
  !.
'PassThruRangeform'(and(_rF1,_rF2),_GenericPred) :-
  'PassThruRangeform'(_rF1,_GenericPred),
  'PassThruRangeform'(_rF2,_GenericPred),
  !.
'PassThruRangeform'(or(_rF1,_rF2),_GenericPred) :-
  'PassThruRangeform'(_rF1,_GenericPred),
  'PassThruRangeform'(_rF2,_GenericPred),
  !.
'PassThruRangeform'(not(_lit),_GenericPred) :-
  'PassThruLits'(negative,[_lit],_GenericPred),
  !.
'PassThruRangeform'('TRUE', _GenericPred) :- !.
'PassThruRangeform'('FALSE', _GenericPred) :- !.
'PassThruRangeform'(_lit, _GenericPred) :-
  _lit =.. [_f|_args],
  \+(member(_f,['forall','exists','and','or','not','TRUE','FALSE'])),
  'PassThruLits'(positive,[_lit],_GenericPred),
  !.
%  If nothing applies: immediate success

'PassThruRangeform'(_anyLit, _anyPred) :- !.
%  Process the calls for a list of CML/Telos literals:
%  _sign: sign of the Literals ('positive' or 'negative') (i)

'PassThruLits'(_sign,[],_GenericPred) :- !.
'PassThruLits'(_sign,[_lit|_rest],_GenericPred) :-
  _GenericPred =.. [_P|_args],
  _callPred =.. [_P,_sign,_lit|_args],
  call(_callPred),
  !,
  'PassThruLits'(_sign,_rest,_GenericPred).
%  ***************************************************************************
%
%  ElimQuant( _Variable, _Formula, _FormulaWithoutQuant)
%
%  The quantification of the given variables is removed from the formula.
%
%  _Variable               : variable whose quantification in the formula
%                            shall be deleted, (i)
%  _Formula                : Formula, (i)
%  _FormulaWithoutQuant    : the same formula but without the quantification of the
%                            variables. (o)
%
%  9-Aug-1990/MJf: adaptation to a more general "range form"
%
%  ***************************************************************************

'ElimQuant'(_var, forall(_vars,_lits,_rangeF),
          forall(_newvars,_lits,_rangeF)) :-
  member(_var,_vars),
  delete(_var,_vars,_newvars),
  !.
'ElimQuant'(_var, forall(_vars,_lits,_rangeF),
          forall(_vars,_lits,_newrangeF)) :-
  'ElimQuant'(_var, _rangeF, _newrangeF),
  !.
%  ... in exists subformulas no quantifier is eliminated anymore, because
%  when literals are deleted one cannot ensure that it remains derivable!
%                                                       9-Aug-1990/MJf

'ElimQuant'(_var, and(_rf1,_rf2), and(_newrf1,_newrf2)) :-
  'ElimQuant'(_var, _rf1, _newrf1),
  'ElimQuant'(_var, _rf2, _newrf2),
  !.
'ElimQuant'(_var, or(_rf1,_rf2), or(_newrf1,_newrf2)) :-
  'ElimQuant'(_var, _rf1, _newrf1),
  'ElimQuant'(_var, _rf2, _newrf2),
  !.
%   .. otherwise (exists, pos/neg literals, TRUE, FALSE): do nothing

'ElimQuant'(_var,_rangeF,_rangeF).
%  ***************************************************************************
%
%  assign_Component( _comp)
%
%  Helper predicate: analogous to assign_ID@validProposition.
%
%  _comp : is assigned a system-defined identifier (o).
%
%  ***************************************************************************

assign_Component(_comp) :-
  newIdentifier(_idNew),
  pc_atomconcat(_idNew,'generated',_comp).  % mark the label with the word 'generated'
%  ===========================================================================
%  ***************************************************************************
%  ***************************************************************************
%
%  *************      S   U   B   M   O   D   U   L   E      *****************
%
%
%                      SSSS  TTTTT   OOO   RRRR   EEEEE
%                     S        T    O   O  R   R  E
%                      SSS     T    O   O  RRRR   EEEE
%                         S    T    O   O  R  R   E
%                     SSSS     T     OOO   R   R  EEEEE
%
%
%  This section contains only predicates concerned with the
%  generation of Prolog predicates.
%  Note: all these predicates are fully analogous to those in the
%  STORE@BDMForget submodule, i.e. if something changes in storage,
%  it must be changed correspondingly there and vice versa!
%
%  The following predicates can be used to store:
%       store_origConstraint( _IcFormulaMerged, _IcId)
%       store_origRule( _RuleCondFormula, _RuleCondFormulaMerged, _RuleConcl,
%                       _RuleId,_ClassId,_ruleinfo)
%       store_applyConstraint( _InsDel, _IcFormulaMerged, _IcId,
%                              _Literal, _ClassId, _SimpIcId)
%       store_applyRule( _InsDel,
%                        _RuleCondMerged, _RuleConcl, _RuleId,
%                        _Literal, _ClassId, _InsDelOfConcl,
%                        _ListOfSimpIcIds, _ListOfSimpRuleIds, _SimpRuleId)
%       store_more_applyConsRule( _InsDel, _SimpRuleId, _ListOfSimpIcIds,
%                                 _ListOfSimpRuleIds)
%
%  ***************************************************************************
%  ***************************************************************************
%  ***************************************************************************
%
%  store_origConstraint( _IcFormula, _IcId)
%
%  generates the propvals and the BDMPredicate for the complete
%  integrity constraint, as it was entered, but already transformed into
%  BDM format with embedded quantifiers (i.e. it is an instance of
%  BDMConstraintCheck).
%
%  _IcFormula : the complete integrity constraint, in BDMFormat with
%               embedded quantifiers (i),
%  _IcId      : the identifier of the object representing the complete integri-
%               ty constraint (i.e. instance of BDMConstraint) (i),
%
%  ***************************************************************************

store_origConstraint( _IcFormula, _IcId) :-
		%  1. Storing the propvals:
		%  1a. Creating an object that contains the integrity constraint
		%      in its internal, complete representation:

	pc_atom_to_term( _IcFormula_flat, _IcFormula),
	disambiguateCodeLabel(_IcFormula_flat,_IcFormula_flat_dollar),
% 	assign_Component( _OrigIcId),

	'STORE'('P'(_OrigIcId,_OrigIcId,_IcFormula_flat_dollar,_OrigIcId)),
	name2id('BDMConstraintCheck',_BDMconChId),
	'STORE'('P'(_IoId1,_OrigIcId,'*instanceof',_BDMconChId)),
		%  1b. Creating a reference from the integrity condition
		%  to their internal, complete representation:

	assign_Component( _Label),
	'STORE'('P'( _ConId, _IcId, _Label, _OrigIcId)),
	retrieve_proposition(
              'P'(_AttrCatId,id_52, originalConstraint, _BDMconChId)),  % id_52=MSFOLconstraint
	'STORE'('P'(_IoId2,_ConId,'*instanceof',_AttrCatId)),
		%  2. Storing the BDM predicate:

	store_BDMFormula('origConstraint@BDMCompile'( _IcId, _OrigIcId, _IcFormula)),  % 26-May-1995 LWEB
	!.
%  ***************************************************************************
%
%  store_origRule( _RuleCondFormulaMerged,
%                  _RuleConcl, _RuleId, _ClassId, _ruleinfo)
%
%  Generates the propvals and the BDM predicate for the complete
%  Rule as it was entered, already transformed into BDMFormat
%  (mixed and unmixed) (i.e. it is an instance of BDMRuleCheck).
%
%  _RuleCondFormula : the complete rule conclusion (i),
%  _RuleCondFormulaMerged : the complete rule conclusion, merged (i),
%  _RuleConcl : the inference literal of the rule (i),
%  _RuleId    : identifier of the object representing the complete rule
%               (i.e. instance of BDMRule) (i),
%  _ClassId   : identifier of the class from which instances can be derived by
%               rules that can be derived (i).
%  _ruleinfo  : range form of the entire rule with ranges and variables (i)
%
%  ***************************************************************************

store_origRule(_RuleCondFormulaMerged, _RuleConcl,
                _RuleId, _ClassId, _ruleinfo) :-
		%  1. Store the propvals:
		%  1a. Creating an object that represents the rule in its
		%  internal, complete format:

	pc_atom_to_term( _Rule_flat,
	    'Rule'( 'Condition'( _RuleCondFormulaMerged), 'Conclusion'( _RuleConcl))),
	disambiguateCodeLabel(_Rule_flat,_Rule_flat_dollar),
	% assign_Component( _OrigRuleId),

	'STORE'('P'(_OrigRuleId,_OrigRuleId,_Rule_flat_dollar,_OrigRuleId)),
	name2id('BDMRuleCheck',_BDMruleChId),
	'STORE'('P'(_IoId1,_OrigRuleId,'*instanceof',_BDMruleChId)),
		%  1b. Create a reference from the rule to its
		%  internal, complete representation:

	assign_Component( _Label2),
	'STORE'('P'(_ConId2,_RuleId,_Label2,_OrigRuleId)),
	retrieve_proposition(
           'P'( _AttrCatId2, id_46, originalRule, _BDMruleChId)),  % id_46=MSFOLrule
	'STORE'('P'(_IoId2,_ConId2,'*instanceof',_AttrCatId2)),
  		%  1c. Create a reference from the class that is affected by the
		%  inference literal of the rule is affected, to the internal
		%  complete rule:

	assign_Component( _Label3),
	'STORE'('P'(_ConId3,_ClassId,_Label3,_OrigRuleId)),
	retrieve_proposition(
                      'P'( _AttrCatId3, id_0, deducedBy, _BDMruleChId)),  % id_0=Proposition
	'STORE'('P'(_IoId3,_ConId3,'*instanceof',_AttrCatId3)),
		%  2. Storing the BDM predicate:

	store_BDMFormula( 'origRule@BDMCompile'( _RuleId, _RuleConcl,_RuleCondFormulaMerged, _ruleinfo)),
	!.
%  ***************************************************************************
%
%  store_applyConstraint( _InsDel,
%                         _IcFormula, _IcId,
%                         _Literal, _ClassId, _SimpIcId,
%                         _StoredForm)
%
%  generates the propvals and the BDM predicate for a specialized integrity-
%  ty constraint.
%
%  _InsDel    : = Insert, if Ic is to be tested during an insert operation,
%               = Delete, "     "  "   "     delete"          "  "      " (i).
%  _IcFormula : the specialized integrity constraint, in mixed
%               BDMFormat (i),
%  _IcId      : the identifier of the object representing the original integri-
%               ty constraint (instance of MSFOLconstraint) (i),
%  _Literal   : with respect to which the Ic was simplified to _IcFormula (i),
%  _ClassId   : id of the class whose instances may match the literal (i),
%  _SimpIcId  : id of the object that represents the simplified Ic (o).
%  _StoredForm: format from constructStoredForm, attached as proposition to the
%               corresponding attribute (i).
%
%  ***************************************************************************

store_applyConstraint( _InsDel,
                       _IcFormula, _IcId,
                       _Literal, _ClassId, _SimpIcId,
                       _StoredForm) :-
		%  1. Store the propvals:
		%  1a. Creating an object that represents the simplified instance
		%  of the integrity constraint:

	pc_atom_to_term( _IcFormula_flat, _StoredForm),
	disambiguateCodeLabel(_IcFormula_flat,_IcFormula_flat_dollar),
% 	assign_Component( _SimpIcId),

	'STORE'('P'(_SimpIcId,_SimpIcId,_IcFormula_flat_dollar,_SimpIcId)),
	name2id('BDMConstraintCheck',_BDMconChId),
	'STORE'('P'(_IoId1,_SimpIcId,'*instanceof',_BDMconChId)),
		%  1b. Create a reference from the integrity condition
		%  to its simplified instance:

	assign_Component( _Label2),
	'STORE'('P'(_ConId2,_IcId,_Label2,_SimpIcId)),
	retrieve_proposition(
             'P'(_AttrCatId2,id_52, specialConstraint, _BDMconChId)),  % id_52=MSFOLconstraint
	'STORE'('P'(_IoId2,_ConId2,'*instanceof',_AttrCatId2)),
		%  1c. Creating a reference from the affected class to
		%  of the simplified instance :

	assign_Component( _Label3),
	'STORE'('P'(_ConId3,_ClassId,_Label3,_SimpIcId)),
	((_InsDel = 'Insert',
	  retrieve_proposition( 'P'( _AttrCatId3,
            id_0, applyConstraintIfInsert,_BDMconChId))  % id_0=Proposition
	 );
	 retrieve_proposition( 'P'( _AttrCatId3,
              id_0, applyConstraintIfDelete, _BDMconChId))  % id_0=Proposition
	),
	'STORE'('P'(_IoId3,_ConId3,'*instanceof',_AttrCatId3)),
		%  2. store the BDM predicate:

	((_InsDel = 'Insert',
	  store_BDMFormula( 'applyConstraintIfInsert@BDMCompile'( _IcId, _ClassId, _SimpIcId, _Literal, _IcFormula))  % 26-May-1995 LWEB
	 );
	 store_BDMFormula( 'applyConstraintIfDelete@BDMCompile'( _IcId, _ClassId, _SimpIcId, _Literal, _IcFormula))
	),
	!.
%  ***************************************************************************
%
%  store_applyRule( _InsDel,
%                   _RuleCondMerged, _RuleConcl, _RuleId,
%                   _Literal, _ClassId, _InsDelOfConcl,
%                   _ListOfSimpIcIds, _ListOfSimpRuleIds, _SimpRuleId)
%
%  Generates the propvals and the BDM predicate for a specialized rule.
%  _InsDel    : = Insert, if the rule is to be executed on an insert operation,
%               = Delete, "     "     "    delete"          "           " (i).
%  _RuleCondMerged: the specialized rule-condition part, in the mixed
%                    BDMFormat (i),
%  _RuleConcl : the inference literal (i),
%  _RuleId    : the identifier of the object that represents the original rule
%               condition (instance of MSFOLrule) represents (i),
%  _Literal   : with respect to which the rule is to be simplified (i),
%  _ClassId   : id of the class whose instances may match the literal (i),
%  _InsDelOfConcl    : indicates the operation that results from _InsDel for the
%                      conclusion literal (i)
%  _ListOfSimpIcIds : list of identifiers of simplified forms of
%                     integrity constraints into which instances of the class
%                     can apply, which through the conclusion literal of the
%                     derived from the current rule may enter (i),
%  _ListOfSimpRuleIds : the same with simplified rules (i).
%  _SimpRuleId        : id of the object representing the simplified rule (o).
%
%  ***************************************************************************

store_applyRule( _InsDel,
                 _RuleCondMerged, _RuleConcl, _RuleId,
	         _Literal, _ClassId, _InsDelOfConcl,
	         _ListOfSimpIcIds, _ListOfSimpRuleIds, _SimpRuleId) :-
		%  1. Storing the propvals:
		%  1a. Create an object representing the simplified form
		%  of the rule:

	pc_atom_to_term( _Rule_flat,
                'Rule'( 'Condition'( _RuleCondMerged), 'Conclusion'( _RuleConcl))),
	disambiguateCodeLabel(_Rule_flat,_Rule_flat_dollar),
% 	assign_Component( _SimpRuleId),

	'STORE'('P'(_SimpRuleId,_SimpRuleId,_Rule_flat_dollar,_SimpRuleId)),
	name2id('BDMRuleCheck',_BDMruleChId),
	'STORE'('P'(_IoId1,_SimpRuleId,'*instanceof',_BDMruleChId)),
		%  1b. Create a reference from the rule to its
		%  simplified form:

	assign_Component( _Label2),
	'STORE'('P'(_ConId2,_RuleId,_Label2,_SimpRuleId)),
	retrieve_proposition(
           'P'(_AttrCatId2, id_46, specialRule, _BDMruleChId)),  % id_46=MSFOLrule
	'STORE'('P'(_IoId2,_ConId2,'*instanceof',_AttrCatId2)),
		%  2. Store the BDM predicate:

	((_InsDel = 'Insert',
	  store_BDMFormula( 'applyRuleIfInsert@BDMCompile'(_RuleId, _ClassId, _SimpRuleId, _Literal, _RuleConcl, _RuleCondMerged,
              goAhead(_InsDelOfConcl,_ListOfSimpIcIds,_ListOfSimpRuleIds)))
	 );
	 store_BDMFormula( 'applyRuleIfDelete@BDMCompile'(_RuleId, _ClassId, _SimpRuleId, _Literal, _RuleConcl, _RuleCondMerged,
              goAhead(_InsDelOfConcl,_ListOfSimpIcIds,_ListOfSimpRuleIds)))
	),
	!.
%  ***************************************************************************
%
%  store_more_applyConsRule( _InsDel, _SimpRuleId,
%                            _ListOfSimpIcIds, _ListOfSimpRuleIds)
%
%  generates the propvals and the modified BDM predicate for a speciali-
%  -zed rule that now enters further integrity tests (in-)directly.
%
%  _InsDel    : = Insert, if rule is to be executed during insert operation,
%               = Delete, "     "     "    delete-"       "           " (i),
%  _SimpRuleId : Id of the object representing the simplified rule (i),
%  _ListOfSimpIcIds : list of identifiers of further simplified forms of
%                     integrity constraints into which instances of the concerned class
%                     may enter, which are derived through the inference literal of the
%                     current rule (i),
%  _ListOfSimpRuleIds : the same with simplified rules (i).
%
%  ***************************************************************************

store_more_applyConsRule( _InsDel, _SimpRuleId, _ListOfSimpIcIds,
	                  _ListOfSimpRuleIds) :-
		%  1. Store the propvals:
		%  2. Storing the BDM predicate:

        (_triggername = 'applyRuleIfInsert@BDMCompile';
         _triggername = 'applyRuleIfDelete@BDMCompile'),
	_trigger =.. [_triggername,_RuleId,_ClassId,_SimpRuleId,_Literal,_RuleConcl,
                      _RuleCondMerged,goAhead(_InsDel,_IClist,_Rulelist)],
	retrieve_BDMFormula_once(_trigger),
        append(_IClist,_ListOfSimpIcIds,_newIClist),
        append(_Rulelist,_ListOfSimpRuleIds,_newRulelist),
	_newtrigger =.. [_triggername,_RuleId, _ClassId,_SimpRuleId,_Literal,_RuleConcl,
                      _RuleCondMerged, goAhead(_InsDel,_newIClist,_newRulelist)],
         'WriteTrace'(veryhigh,'BDMCompile', ['Simplified rule ',idterm(_SimpRuleId),
                   ' gets new go-ahead triggers to simplified constraints "',
                   idterm(_ListOfSimpIcIds), '" and rules "',idterm(_ListOfSimpRuleIds),'"']),
       change_BDMFormula(_trigger,_newtrigger),
	!.
% AM : Storing the simplified rangeform instead

constructStoredForm(_simplifiedrangeform,_ranges,_InsDel,_lit,_InstLiteral,_StoredForm) :-
  create_replaceList(_lit,_InstLiteral,_rpl),
  listreplace(_simplifiedrangeform,_rpl,_sfr_new),
  ((_InsDel == 'Insert',
    _StoredForm = 'Insert'(_InstLiteral,_sfr_new,_ranges));
   (_InsDel == 'Delete',
    _StoredForm = 'Delete'(_InstLiteral,_sfr_new,_ranges))
  ).
%  for the next two clauses cf. ErrorsCorrected[11]

create_replaceList(_lit,'Adot'(_cc,_s,_d),_rpl) :-
	!,
	id2name(_cc,_l),
	create_replaceList(_lit,'A'(_s,_l,_d),_rpl).
create_replaceList(_lit,'Aidot'(_,_s,_d),_rpl) :-
	!,
	create_replaceList(_lit,'Ai'(_s,_l,_d),_rpl).
%  otherwise continue as before

create_replaceList(_lit,_InstLiteral,_rpl) :-
  _lit =.. [_|_args1],
  _InstLiteral =.. [_|_args2],
  scan_for_vars(_args2,_args1,_rpl).

scan_for_vars(_,[],[]) :- !.
scan_for_vars([],_,[]) :- !.
scan_for_vars([_top_arg2|_rest_args2],[_top_arg1|_rest_args1],[by(_top_arg1,_top_arg2)|_rpl_rest]) :-
  var(_top_arg2),!,
  scan_for_vars(_rest_args2,_rest_args1,_rpl_rest).
scan_for_vars([_top_arg2|_rest_args2],[_top_arg1|_rest_args1],_rpl_rest) :-
  ground(_top_arg2),!,
  scan_for_vars(_rest_args2,_rest_args1,_rpl_rest).

listreplace(_simplifiedrangeform,[_top_rpl|_rest_rpl],_sfr_new) :-
  !,
  replace(_simplifiedrangeform,_top_rpl,_sfr_new1),
  listreplace(_sfr_new1,_rest_rpl,_sfr_new).
listreplace(_simplifiedrangeform,[],_simplifiedrangeform) :- !.

replace(_simplifiedrangeform,by(_a,_b),_sfr_new) :-
  (atom(_simplifiedrangeform);
   var(_simplifiedrangeform)),
  ((_simplifiedrangeform == _a,
    _sfr_new = _b);
   (_sfr_new = _simplifiedrangeform)),
  !.
replace(_simplifiedrangeform,by(_a,_b),_sfr_new) :-
  _simplifiedrangeform =.. [_f|_args],
  replaceTermList(_args,by(_a,_b),_args_new),
  _sfr_new =.. [_f|_args_new] .

replaceTermList([],by(_a,_b),[]) :- !.
replaceTermList([_top_arg|_args],by(_a,_b),[_top_arg_new|_args_new]) :-
  !,
  replace(_top_arg,by(_a,_b),_top_arg_new),
  replaceTermList(_args,by(_a,_b),_args_new).
%  Ticket #161: create a save object name for _rawtext: if such an object already
%  exists, then we append a comment text with the identifier _idX to make it
%  unique. This ensures that triggers like applyRuleIfInsert will get a unique
%  identifier being the object identifier of the Telos proposition generated for
%  _savetext_dollar.

disambiguateCodeLabel(_rawtext,_savetext_dollar) :-
  atom(_rawtext),
  pc_atomconcat(['$',_rawtext,'$'], _rawtext_dollar),
  do_disambiguateCodeLabel(_rawtext_dollar,_savetext_dollar).

do_disambiguateCodeLabel(_rawtext_dollar,_savetext_dollar) :-
  retrieve_proposition('P'(_id,_id,_rawtext_dollar,_id)),  % object with rawtext_dollar already exists
  !,
  newIdentifier(_idX),  % see ticket #161
  pc_atomconcat([_rawtext_dollar,' /* disambiguated ',_idX,' */'],_savetext_dollar).
%  else: the original code label can be used

do_disambiguateCodeLabel(_text_dollar,_text_dollar).
