.TH CBGRAPH 1 "June 2026" "ConceptBase.cc" "User Commands"
.SH NAME
cbgraph \- ConceptBase graph editor
.SH SYNOPSIS
.B cbgraph
.SH DESCRIPTION
.B cbgraph
launches the standalone ConceptBase graph editor (\fBCBEditor\fR). Connect to
a running server from the File menu or start a server with \fBcbserver\fR first.
.SH ENVIRONMENT
.TP
.B CB_HOME
Client installation root.
.TP
.B CB_PORTNR
Default server port when connecting (4001).
.SH SEE ALSO
.BR cbiva (1),
.BR cbserver (1)
