.TH CBIVA 1 "June 2026" "ConceptBase.cc" "User Commands"
.SH NAME
cbiva \- ConceptBase workbench (IVA desktop client)
.SH SYNOPSIS
.B cbiva
.SH DESCRIPTION
.B cbiva
starts the ConceptBase Workbench desktop application (\fBCBIva\fR), the primary
graphical client for browsing, editing, and querying knowledge bases.
.SH ENVIRONMENT
.TP
.B CB_HOME
Client installation root.
.TP
.B CB_PORTNR
Default server port when connecting (4001).
.SH SEE ALSO
.BR cbgraph (1),
.BR cbshell (1),
.BR cbserver (1)
