= Export Models As Graphviz Specifications

Verified independently via:

```bash
nix build .#checks.x86_64-linux.export-models-as-graphviz-specifications
```

== Input

=== `ConceptBase Tutorial 3/cbtutorial3-all.cbs.txt`

```telos
# This file is governed by the Creative Commons license
#   attributeion-NonCommercial 3.0 Unported
#   http://creativecommons.org/licenses/by-nc/3.0/
#   http://creativecommons.org/licenses/by-nc/3.0/legalcode
#
# Extended licenses, in particular commercial licenses, can be obtained from the
# author of the source code.
# Any re-distribution as source code must acknowledge the original author of this file.

#
# File: cbtutorial3-all.cbs
# Author: Manfred Jeusfeld
# Created: 2013-04-25/M.Jeusfeld (2016-05-11/M.Jeusfeld)
# ------------------------------------------------------
#
# Commands of the ConceptBase Tutorial 3 (combines script1 and script2)
#
# Start: cbshell cbtutorial3-all.cbs


# connect to the CBserver (either started on the fly or public CBserver)
connect

tell '
    Place with
      attribute sendsToken: Transition;
      marks: Integer {* defines markings *}
    end

    Transition with 
      attribute producesToken : Place 
    end
'


tell '
    PNElement end
    Place isA PNElement end
    Transition isA PNElement end
    Place!sendsToken isA PNElement end
    Transition!producesToken isA PNElement end

    PNModel in Class with
      attribute
        contains: PNElement
      rule
        r1: $ forall p/Place m/PNModel a/Place!sendsToken
            (m contains p) and Ai(p,sendsToken,a)
            ==> (m contains a) $;
        r2: $ forall t/Transition m/PNModel a/Transition!producesToken
            (m contains t) and Ai(t,producesToken,a) 
            ==> (m contains a) $
    end
'

tell '
    red1 in Place with
      sendsToken
        t1: rg1
    end

    yellow1 in Place with
      sendsToken
        t1: yr1
    end

    green1 in Place with
      sendsToken
        t1: gy1
    end

    safe1 in Place with
      sendsToken
        t1: rg1
    end

    yr1 in Transition with
      producesToken
        p1: red1;
        p2: safe2
    end

    rg1 in Transition with
      producesToken
        p1: green1
    end

    gy1 in Transition with
      producesToken
        p1: yellow1
    end


    red2 in Place with
      sendsToken
        t1: rg2
    end

    yellow2 in Place with
      sendsToken
        t1: yr2
    end

    green2 in Place with
      sendsToken
        t1: gy2
    end

    safe2 in Place with
      sendsToken
        t1: rg2
    end

    yr2 in Transition with
      producesToken
        p1: red2;
        p2: safe1
    end

    rg2 in Transition with
      producesToken
        p1: green2
    end

    gy2 in Transition with
      producesToken
        p1: yellow2
    end

    TrafficLights in PNModel with
      contains
       e1: red1;
       e2: yellow1;
       e3: green1;
       e4: safe1;
       e5: red2;
       e6: yellow2;
       e7: green2;
       e8: safe2;
       e9: yr1;
       e10: rg1;
       e11: gy1;
       e12: yr2;
       e13: rg2;
       e14: gy2
    end
'


tell '
    BOXNODE_FORMAT in AnswerFormat with
       pattern p:
         "node [shape=box]; {Foreach( ({this.elem}), (n), {n};)}"
    end

    CIRCLENODE_FORMAT in AnswerFormat with
       pattern p: 
        "node [shape=circle,fixedsize=true,width=0.9]; {Foreach( ({this.elem}), (n), {n};)}"
    end

    LINK_FORMAT in AnswerFormat with
       pattern p: 
         "{Foreach( ({this.elem}),(l),{From({l})}->{To({l})};\\n)}"
    end
'


tell '
    GenericQueryClass ShowElement isA PNModel with
      required,parameter
         pn: PNModel;
         type: Proposition
      computed_attribute
         elem: PNElement
     constraint
         c1: $ (pn = this) and
               (this contains elem) and
               (elem in type) $
    end
'


tell '
    GenericQueryClass ShowPN isA PNModel with
      required,parameter
         pn: PNModel
      constraint
         c1: $ (pn = this) $
    end

    GraphVizPN in AnswerFormat with
      forQuery q: ShowPN
      head h: "
# Generated by ConceptBase {cb_version} at {transactiontime}
# Process this file by Graphviz, e.g. 
#    neato -Tpng thisfile.txt > thisfile.png

"
      pattern p: "
digraph {this} \{
{ASKquery(ShowElement[{this}/pn,Transition/type],BOXNODE_FORMAT)}
{ASKquery(ShowElement[{this}/pn,Place/type],CIRCLENODE_FORMAT)}
{ASKquery(ShowElement[{this}/pn,Place!sendsToken/type],LINK_FORMAT)}
{ASKquery(ShowElement[{this}/pn,Transition!producesToken/type],LINK_FORMAT)}
overlap=false
label=\"PetriNet Model {this}\\\nExtracted from ConceptBase and layed out by Graphviz \"
fontsize=12;
\}
"
    end
'

# Extract the GraphViz code for layouting the example petri net 'TrafficLights'
ask ShowPN[TrafficLights/pn] OBJNAMES GraphVizPN
showAnswer







```

=== `ConceptBase Tutorial 3/cbtutorial3-script1.cbs.txt`

```telos
# This file is governed by the Creative Commons license
#   attributeion-NonCommercial 3.0 Unported
#   http://creativecommons.org/licenses/by-nc/3.0/
#   http://creativecommons.org/licenses/by-nc/3.0/legalcode
#
# Extended licenses, in particular commercial licenses, can be obtained from the
# author of the source code.
# Any re-distribution as source code must acknowledge the original author of this file.

#
# File: cbtutorial3-script1.cbs
# Author: Manfred Jeusfeld
# Created: 2013-04-25/M.Jeusfeld (2013-04-26/M.Jeusfeld)
# ------------------------------------------------------
#
# Commands of the ConceptBase Tutorial 3
#
# Start: cbshell cbtutorial3-script1.cbs


cbserver -db PETRINETS

tell '
    Place with
      attribute sendsToken: Transition;
      marks: Integer {* defines markings *}
    end

    Transition with 
      attribute producesToken : Place 
    end
'


tell '
    PNElement end
    Place isA PNElement end
    Transition isA PNElement end
    Place!sendsToken isA PNElement end
    Transition!producesToken isA PNElement end

    PNModel in Class with
      attribute
        contains: PNElement
      rule
        r1: $ forall p/Place m/PNModel a/Place!sendsToken
            (m contains p) and Ai(p,sendsToken,a)
            ==> (m contains a) $;
        r2: $ forall t/Transition m/PNModel a/Transition!producesToken
            (m contains t) and Ai(t,producesToken,a) 
            ==> (m contains a) $
    end
'

tell '
    red1 in Place with
      sendsToken
        t1: rg1
    end

    yellow1 in Place with
      sendsToken
        t1: yr1
    end

    green1 in Place with
      sendsToken
        t1: gy1
    end

    safe1 in Place with
      sendsToken
        t1: rg1
    end

    yr1 in Transition with
      producesToken
        p1: red1;
        p2: safe2
    end

    rg1 in Transition with
      producesToken
        p1: green1
    end

    gy1 in Transition with
      producesToken
        p1: yellow1
    end


    red2 in Place with
      sendsToken
        t1: rg2
    end

    yellow2 in Place with
      sendsToken
        t1: yr2
    end

    green2 in Place with
      sendsToken
        t1: gy2
    end

    safe2 in Place with
      sendsToken
        t1: rg2
    end

    yr2 in Transition with
      producesToken
        p1: red2;
        p2: safe1
    end

    rg2 in Transition with
      producesToken
        p1: green2
    end

    gy2 in Transition with
      producesToken
        p1: yellow2
    end

    TrafficLights in PNModel with
      contains
       e1: red1;
       e2: yellow1;
       e3: green1;
       e4: safe1;
       e5: red2;
       e6: yellow2;
       e7: green2;
       e8: safe2;
       e9: yr1;
       e10: rg1;
       e11: gy1;
       e12: yr2;
       e13: rg2;
       e14: gy2
    end
'


tell '
    BOXNODE_FORMAT in AnswerFormat with
       pattern p:
         "node [shape=box]; {Foreach( ({this.elem}), (n), {n};)}"
    end

    CIRCLENODE_FORMAT in AnswerFormat with
       pattern p: 
        "node [shape=circle,fixedsize=true,width=0.9]; {Foreach( ({this.elem}), (n), {n};)}"
    end

    LINK_FORMAT in AnswerFormat with
       pattern p: 
         "{Foreach( ({this.elem}),(l),{From({l})}->{To({l})};\\n)}"
    end
'


tell '
    GenericQueryClass ShowElement isA PNModel with
      required,parameter
         pn: PNModel;
         type: Proposition
      computed_attribute
         elem: PNElement
     constraint
         c1: $ (pn = this) and
               (this contains elem) and
               (elem in type) $
    end
'

ask ShowElement[TrafficLights/pn,Place/type] OBJNAMES FRAME


ask ShowElement[TrafficLights/pn,Place/type] OBJNAMES CIRCLENODE_FORMAT



tell '
    GenericQueryClass ShowPN isA PNModel with
      required,parameter
         pn: PNModel
      constraint
         c1: $ (pn = this) $
    end

    GraphVizPN in AnswerFormat with
      forQuery q: ShowPN
      head h: "
# Generated by ConceptBase {cb_version} at {transactiontime}
# Process this file by Graphviz, e.g. 
#    neato -Tpng thisfile.txt > thisfile.png

"
      pattern p: "
digraph {this} \{
{ASKquery(ShowElement[{this}/pn,Transition/type],BOXNODE_FORMAT)}
{ASKquery(ShowElement[{this}/pn,Place/type],CIRCLENODE_FORMAT)}
{ASKquery(ShowElement[{this}/pn,Place!sendsToken/type],LINK_FORMAT)}
{ASKquery(ShowElement[{this}/pn,Transition!producesToken/type],LINK_FORMAT)}
overlap=false
label=\"PetriNet Model {this}\\\nExtracted from ConceptBase and layed out by Graphviz \"
fontsize=12;
\}
"
    end
'








```

=== `ConceptBase Tutorial 3/cbtutorial3-script2.cbs.txt`

```telos
# This file is governed by the Creative Commons license
#   attributeion-NonCommercial 3.0 Unported
#   http://creativecommons.org/licenses/by-nc/3.0/
#   http://creativecommons.org/licenses/by-nc/3.0/legalcode
#
# Extended licenses, in particular commercial licenses, can be obtained from the
# author of the source code.
# Any re-distribution as source code must acknowledge the original author of this file.

#
# File: cbtutorial3-script2.cbs
# Author: Manfred Jeusfeld
# Created: 2013-04-25/M.Jeusfeld (2013-04-26/M.Jeusfeld)
# ------------------------------------------------------
#
# Commands of the ConceptBase Tutorial 3
# We assume that you executed cbtutorial3-script1.cbs before.
# It creates a database PETRINETS.
#
# Start: cbshell cbtutorial3-script2.cbs
# 
# If you have GraphViz instaalled on your computer, you can pipe the
# answer directly into a suitable GraphViz layout program, e.g.
#
# cbshell cbtutorial3-script2.cbs | neato -Tpng > pn1.png
#
# The petri net model is then in the PNG graphics file pn1.png
#


cbserver -t no -db PETRINETS

ask ShowPN[TrafficLights/pn] OBJNAMES GraphVizPN
showAnswer






```

=== `for ERD diagrams/ERD-graphviz2.sml.txt`

```telos
{*
* File ERD-graphviz2.sml
* Author: Manfred Jeusfeld, manfred.jeusfeld@acm.org
* Date: 5-Jun-2008 (5-Apr-2016)
*----------------------------------------------------------------
* This model file specifies the ERD notation and provides and
* export filter for graphviz.
* Steps:
*  1- Load this model into ConceptBase
*  2- Load the example model UniversityModel.sml into ConceptBase
*  3- Ask the query ShowERD[UniversityModel/erd]
*  4- Copy/paste the answer to a file graphviz-input.dot
*  5- Call Graphviz, e.g. by
*       neato -Tpng graphviz-input.dot > graphviz-output.png
* Use the manual pages of dot or neato to learn more about options of Graphviz.
* Graphviz is available from http://graphviz.org/
*
* (c) 2008 by M. Jeusfeld. 
* This model file is licensed under the terms of attributeion-Non-Commercial 2.0 Germany 
*   http://creativecommons.org/licenses/by-nc/2.0/de/legalcode  (German)
*   http://creativecommons.org/licenses/by-nc/2.0/legalcode     (generic)
* A summary of your rights and obligations concerning this work is available from
*   http://creativecommons.org/licenses/by-nc/2.0/de/deed.en_GB
* Extended rights can be obtained via the author.
*
* Requires ConceptBase 7.1.2 released 9-Jul-2008 or later.
*
*}


{* -------------------------------------------------------------------------- *}
{* Define the ERD notation:                                                   *}
{*  entity types, relationship types, IsA types, cardinality tags, attributes *}
{* -------------------------------------------------------------------------- *}

EntityType with
  attribute
    attr: Domain;
    key: Domain;   {* some attributes are key attributes *}
    superType: EntityType  {* only used for defining the semaantics of the IsaType *}
end


RelationshipType with
  attribute
    role: EntityType;
    "1..n": EntityType;
    "1..1": EntityType;
    "0..1": EntityType;
    "0..n": EntityType;
    "n..m": EntityType
end


Proposition with
  attribute
    cardinalityTag: Proposition
end


RelationshipType!"1..n" in Proposition!cardinalityTag end
RelationshipType!"1..1" in Proposition!cardinalityTag end
RelationshipType!"0..1" in Proposition!cardinalityTag end
RelationshipType!"0..n" in Proposition!cardinalityTag end
RelationshipType!"n..m" in Proposition!cardinalityTag end

{* This one is what Yourdan calls an associative object type *}
EntityRelationshipType in Class isA EntityType,RelationshipType
end

IsaType in Class with
  attribute 
    sub: EntityType;
    super: EntityType
end


Domain with
end

IsaType with
  rule
    makeBinaryRel: $ forall I/IsaType E1,E2/EntityType
                        (I sub E1) and (I super E2)  ==> (E1 superType E2) $;
    membershipRule: $ forall e/VAR E,D/EntityType
                       (e in D) and (D superType E)  ==> (e in E) $
end

Integer in Domain end
String in Domain end
Date in Domain end
Real in Domain end

{* -------------------------------------------------------------------------- *}
{* ERD elements are just all elements that can occur in an ER diagram         *}
{* -------------------------------------------------------------------------- *}

ERDElement end
EntityType isA ERDElement end
RelationshipType isA ERDElement end
RelationshipType!role isA ERDElement end
IsaType isA ERDElement end
IsaType!sub isA ERDElement end
IsaType!super isA ERDElement end
Domain isA ERDElement end
EntityType!attr isA ERDElement end

ERDModel in Class with
  attribute
    contains: ERDElement
  rule
    r1: $ forall e/EntityType m/ERDModel a/EntityType!attr
             (m contains e) and Ai(e,attr,a) ==> (m contains a) $;
    r2: $ forall e/IsaType m/ERDModel a/IsaType!sub
             (m contains e) and Ai(e,sub,a) ==> (m contains a) $;
    r3: $ forall e/IsaType m/ERDModel a/IsaType!super
             (m contains e) and Ai(e,super,a) ==> (m contains a) $;
    r4: $ forall e/RelationshipType m/ERDModel a/RelationshipType!role
             (m contains e) and Ai(e,role,a) ==> (m contains a) $
end






{* -------------------------------------------------------------------------- *}
{* We  support the following graphical notation for ERDs:                     *}
{* Entity types                 --> boxes                                     *}
{* Relationship types           --> diamonds                                  *}
{* Entityrelationship types     --> squared diamonds                          *}
{* IsA types                    --> diamonds with grey color                  *}
{* entity attributes            --> ellipses                                  *}
{* key attributes               --> ellipses with double lines                *}
{* roles links                  --> undirected links                          *}
{* links to subtypes            --> undirected links                          *}
{* links to supertypes          --> undirected links with a bar               *}
{* attribute links              --> undirected links                          *}
{* -------------------------------------------------------------------------- *}

GraphVizType end

Boxnode in GraphVizType,Class with
  rule
    r1: $ forall n/EntityType not (n in EntityRelationshipType) ==> (n in Boxnode) $
end
Diamondnode in GraphVizType,Class with
  rule
    r1: $ forall n/RelationshipType not (n in EntityType) ==> (n in Diamondnode) $
end
Mdiamondnode in GraphVizType,Class with
  rule
    r1: $ forall n/EntityRelationshipType (n in Mdiamondnode) $
end
Filleddiamondnode in GraphVizType,Class with
  rule
    r1: $ forall n/IsaType (n in Filleddiamondnode) $
end
Ellipsenode in GraphVizType,Class with
  rule
    r1: $ forall n/EntityType!attr not (n in EntityType!key) ==> (n in Ellipsenode) $
end
Dellipsenode in GraphVizType,Class with
  rule
    r1: $ forall n/EntityType!key (n in Dellipsenode) $
end
Link in GraphVizType,Class with
  rule
    r1: $ forall l/RelationshipType!role (l in Link) $;
    r2: $ forall l/IsaType!sub (l in Link) $
end
LinkTee in GraphVizType,Class with
  rule
    r1: $ forall l/IsaType!super (l in LinkTee) $
end
LinkAttr in GraphVizType,Class with
  rule
    r1: $ forall l/EntityType!attr (l in LinkAttr) $
end


{* -------------------------------------------------------------------------- *}
{* LinkLabel returns the cardinality tag of a role link; if the tag is        *}
{* undefined then the empty string is returned.                               *}
{* -------------------------------------------------------------------------- *}

Function LinkLabel isA Label with
  parameter
     li: Link
  constraint
     cfn: $ (exists tag1/Proposition!cardinalityTag (li in RelationshipType!role) and (li in tag1) and Label(tag1,this))
            or (not exists tag2/Proposition!cardinalityTag (li in RelationshipType!role) and (li in tag2)) and (this ="")
          $
end


{* -------------------------------------------------------------------------- *}
{* ShowERD returns the parameter erd as result. This is apparently not very   *}
{* meaningful but is triggers the evaluation of the answer format script      *}
{* GraphVizErd, which coordinates the production of the answer.               *}
{* -------------------------------------------------------------------------- *}

GenericQueryClass ShowERD isA ERDModel with
  required,parameter
     erd: ERDModel
  constraint
     c1: $ (erd = this) $
end


{* -------------------------------------------------------------------------- *}
{* ShowElement(erd,type) computes those elements that are contained in a      *}
{* given ERD diagram erd and that have the given type (e.g. Boxnode).         *}
{* It is used to format all elements of an ERD to their Graphviz              *}
{* representation.                                                            *}
{* -------------------------------------------------------------------------- *}

GenericQueryClass ShowElement isA ERDModel with
  required,parameter
     erd: ERDModel;
     type: GraphVizType
  computed_attribute
     elem: ERDElement
 constraint
     c1: $ (erd = this) and
           (this contains elem) and
           (elem in type) $
end


{* -------------------------------------------------------------------------- *}
{* GraphVizErd coordinates the production of all Graphviz code for an ER      *}
{* diagram. It does so by calling ShowElement for all supported types.        *}
{* -------------------------------------------------------------------------- *}

GraphVizErd in AnswerFormat with
  forQuery q: ShowERD
  head h: 
"# Generated by ConceptBase {cb_version} at {transactiontime}
# Process this file by Graphviz, e.g. 
#    neato -Tpng thisfile.txt > thisfile.png

"
  pattern p:
"graph {this} \{
{ASKquery(ShowElement[{this}/erd,Boxnode/type],BOXNODE_FORMAT)}
{ASKquery(ShowElement[{this}/erd,Diamondnode/type],DIAMONDNODE_FORMAT)}
{ASKquery(ShowElement[{this}/erd,Mdiamondnode/type],MDIAMONDNODE_FORMAT)}
{ASKquery(ShowElement[{this}/erd,Dellipsenode/type],DELLIPSENODE_FORMAT)}
{ASKquery(ShowElement[{this}/erd,Ellipsenode/type],ELLIPSENODE_FORMAT)}
{ASKquery(ShowElement[{this}/erd,Filleddiamondnode/type],FILLEDDIAMONDNODE_FORMAT)}
{ASKquery(ShowElement[{this}/erd,link/type],LINK_FORMAT)}
{ASKquery(ShowElement[{this}/erd,LinkTee/type],LINKTEE_FORMAT)}
{ASKquery(ShowElement[{this}/erd,LinkAttr/type],LINKATTR_FORMAT)}
overlap=false
label=\"ERD Model {this}\\\nExtracted from ConceptBase and layed out by Graphviz (neato) \"
fontsize=12;
\}
"
end


{* -------------------------------------------------------------------------- *}
{* The following answer formats are linked one-to-one to the supported        *}
{* Graphviz types (Boxnode,...).                                              *}
{* Note that a given ERD referenced by 'this' usually has many elements of    *}
{* a given type. They are scanned by the Foreach-construct.                   *}
{* -------------------------------------------------------------------------- *}

BOXNODE_FORMAT in AnswerFormat with
pattern p: "node [shape=box]; {Foreach( ({this.elem}), (n), {n};)}"
end

DIAMONDNODE_FORMAT in AnswerFormat with
pattern p: "node [shape=diamond]; {Foreach( ({this.elem}), (d), {d};)}"
end

FILLEDDIAMONDNODE_FORMAT in AnswerFormat with
pattern p: "node [shape=diamond,style=filled,peripheries=1,color=lightgrey,label=\"isa\"]; {Foreach( ({this.elem}), (f), {f};)}"
end

ELLIPSENODE_FORMAT in AnswerFormat with
pattern p: "{Foreach( ({this.elem}), (e),node [shape=ellipse,peripheries=1,label=\"{Label({e})}\"]; {Oid({e})};\\n)}"
end

DELLIPSENODE_FORMAT in AnswerFormat with
pattern p: "{Foreach( ({this.elem}), (e),node [shape=ellipse,peripheries=2,label=\"{Label({e})}\"]; {Oid({e})};\\n)}"
end


MDIAMONDNODE_FORMAT in AnswerFormat with
pattern p: "node [shape=Mdiamond]; {Foreach( ({this.elem}), (m), {m};)}"
end

LINK_FORMAT in AnswerFormat with
pattern p: "{Foreach( ({this.elem}),(l),{From({l})}--{To({l})} [len=1.20,label={ASKquery(LinkLabel[{l}/li],LABEL)}];\\n)}"
end

LINKTEE_FORMAT in AnswerFormat with
pattern p: "{Foreach( ({this.elem}),(l),{From({l})}--{To({l})} [len=1.10,dir=forward,arrowhead=tee];\\n)}"
end

LINKATTR_FORMAT in AnswerFormat with
pattern p: "{Foreach( ({this.elem}),(l),{From({l})}--{Oid({l})} [len=1.00];\\n)}"
end




```

=== `for ERD diagrams/ERD-graphviz.sml.txt`

```telos
{*
This file is governed by the Creative Commons license
   attributeion-NonCommercial 3.0 Unported
   http://creativecommons.org/licenses/by-nc/3.0/
   http://creativecommons.org/licenses/by-nc/3.0/legalcode

Extended licenses, in particular commercial licenses, can be obtained from the
author of the source code.
Any re-distribution as source code must acknowledge the original author of this file.
*}


{*
* File ERD-graphviz.sml
* Author: Manfred Jeusfeld, jeusfeld@uvt.nl
* Date: 5-Jun-2008 (21-Feb-2011)
*----------------------------------------------------------------
* This file specifies the ERD notation and provides and
* export filter for graphviz. You need to install the GraphViz package.
* It contains several layout routines such as dot and neato.
* Manual steps:
*  1- Load this model into ConceptBase
*  2- Ask the query ShowERD[MyModel1/erd]
*  3- Copy/pase the answer to a file mygv.txt
*  4- Call GraphViz, e.g. by
*       dot -Tpng mygv.txt > mygv.png
* Use the manual pages of dot to learn more about options of GraphViz.
* GraphViz is available from 
*   http://graphviz.org/
*
* You can also automate the generation of the dot files by starting the
* CBserver with the option -views <dir>. The directory <dir> will
* then contain files <Model>.dot for each instance of ERDModel. 
* 
* Requires ConceptBase 7.3.06 released 2011-02-21 or later.
*}


{*** NOTATION DEFINITION LEVEL *}

Node with
  attribute
    connectedTo: Node
end


{*** NOTATION LEVEL       *}
{*** ER notation with cardinalities *}

EntityType in Node with
end

RelationshipType in Node with
  connectedTo
     role: EntityType
end

RelationshipType!role with
  attribute
     card: Cardinality
end

Cardinality in Node end

{* we support here just three cardinalities *}
"1..1" in Cardinality end
"0..1" in Cardinality end
"1..*" in Cardinality end

ERDElement in Node end

EntityType isA ERDElement end
RelationshipType isA ERDElement end
RelationshipType!role isA ERDElement end

ERDModel with
  attribute
    contains: ERDElement
end




{*** MODEL LEVEL *}
{*** this defines an example ER diagram using the above ER notation *}



Employee in EntityType with   {* shall match variable ET1 *}
end

Project in EntityType with   {* ET2 *}
end

worksFor in RelationshipType with   {* RT *}
  role
   toEmp: Employee;
   toProj: Project
end

worksFor!toEmp with   {* R1 *}
  card
    card1: "1..*"  {* each project has at least 1 employee who works for it *}
end

worksFor!toProj with  {* R2 *}
  card
    card1: "0..1"   {* each employee works in at most 1 project *}
end

MyModel1 in ERDModel with
  contains
    e1: Employee;
    e2: Project;
    e3: worksFor;
    e4: worksFor!toEmp;
    e5: worksFor!toProj
end

Boxnode in QueryClass isA EntityType end
Diamondnode in QueryClass isA RelationshipType end
Link in QueryClass isA RelationshipType!role end


GenericQueryClass FromNode isA Individual with
  parameter
     lnk: attributee
  constraint
     cfn: $ From(lnk,this) $
end

GenericQueryClass ToNode isA Individual with
  parameter
     lnk: attributee
  constraint
     cfn: $ To(lnk,this) $
end


GenericQueryClass ShowERD isA ERDModel with
  required,parameter
     erd: ERDModel
  computed_attribute
     boxnode: Boxnode;
     diamondnode: Diamondnode;
     link: Link
  constraint
     c1: $ (erd = this) and
           (this contains boxnode) and
           (this contains diamondnode) and
           (this contains link) $
end

GraphVizErd in AnswerFormat with
  forQuery q: ShowERD
  head h: "graph ER \{"
  pattern p:
"node [shape=box]; {Foreach( ({this.boxnode}), (n), {n};)}
node [shape=diamond]; {Foreach( ({this.diamondnode}), (d), {d};)}
{Foreach( ({this.link}),(l), {ASKquery(FromNode[{l}/lnk],LABEL)}--{ASKquery(ToNode[{l}/lnk],LABEL)};\\n)}
#label=\"ERD Model {this}\"
fontsize=20;
"
  tail t: "\}"
  fileType ty: "dot"
end



{* save ShowERD in this and all other (sub-)modules *}
Module in Class with
  rule
    rsaveView: $ forall m/Module (m saveView ShowERD) $
end
 




```

=== `for ERD diagrams/gvtest.cbs.txt`

```telos
# sample script to test the generation og GraphViz code via a query with answer format
# M. Jeusfeld,  2008-06-25 (2016-05-13)
connect
tellModel ERD-graphviz2
tellModel UniversityModel
ask ShowERD[UniversityModel/erd] OBJNAMES FRAME Now
showAnswer
exit


```

=== `for ERD diagrams/UniversityModel.sml.txt`

```telos


{*** UniversityModel.sml *}
{*** this defines an example ER diagram using the ER notation *}
{*** of ERD-graphviz2.sml                                     *}


EntityType Staff with
  attr
    name: String;
    hired: Date;
    salary: Integer
  attr,key
   staffno: Integer
end

EntityType Faculty with
  attr
    since: Date;
    post: String
end

EntityType Technician with
  attr
    since: Date;
    post: String
end



EntityType Student with
  attr
    since: Date
  attr,key
    studentid: Integer
end


EntityType University with
  attr, key
   name: String;
   location: String
end

EntityType Course with
  attr,key
    courseno: Integer;
    semester: String
  attr
    title: String
end

RelationshipType employs with
  role,"0..n"
    employee: Staff
  role,"1..1"
    employer: University
end

IsaType ISA_1 with 
  sub
    sub1: Faculty;
    sub2: Technician
  super
     super1: Staff
end


RelationshipType teaches with
  role,"1..1"
    teacher: Faculty
  role
    subject: Course
end


EntityRelationshipType attends with
  role
    stud: Student;
    course: Course
  attr
    quota: Integer
end




UniversityModel in ERDModel with
  contains
    e1: Staff;
    e2: Faculty;
    e3: Technician;
    e4: Student;
    e5: University;
    e6: Course;
    e7: employs;
    e8: teaches;
    e9: attends;
    e10: ISA_1
end

```

=== `for Large Models/BF-viz.sml.txt`

```telos
{*
* File BF-viz.sml
* Author: Manfred Jeusfeld, jeusfeld@uvt.nl
* Date: 18-Jun-2008 (18-Jun-2008)
*----------------------------------------------------------------
* This file specifies the BigFlights notation and provides and
* export filter for graphviz.
* Steps:
*  1- Load this model into ConceptBase
*  2- Load the example model BigFlights.sml into ConceptBase
*  3- Ask the query ShowBF[bf/model]
*  4- Copy/paste the answer to a file graphviz-input.dot
*  5- Call GraphViz, e.g. by
*       neato -Tpng graphviz-input.dot > graphviz-output.png
* Use the manual pages of dot or neato to learn more about options of GraphViz.
* GraphViz is available from 
*   http://graphviz.org/
*
* Requires ConceptBase 7.1 released 17-Jun-2008 or later.
*
*}

Individual city in Class with
   attribute
        con_to : city
end


Element end
city isA Element end
city!con_to isA Element end

Connection in GenericQueryClass isA city!con_to with 
  parameter
    c1: city; c2: city
  constraint
    cstr: $ From(this,c1) and To(this,c2) $
end


BFModel end

bf in BFModel end


BFModel in Class with
  attribute
    contains: Element
  rule
    r1: $ forall c/city (bf contains c) $;
    r2: $ forall c,d/city con/selectfirst[Connection[c,d]] (bf contains con) $
{*  r2: $ forall c/city!con_to (bf contains c) $ *}
end


{* We define at meta meta class level some language constructs to express constraints at *}
{* the model level. That means: we constrain the set of allowed ER diagrams (=syntax     *}
{* constraints). All formulas are meta-level formulas.                                   *}






GraphVizType end

Ellipsenode in GraphVizType,Class with
  rule
    r1: $ forall n/city (n in Ellipsenode) $
end
Link in GraphVizType,Class with
  rule
    r1: $ forall l/city!con_to (l in Link) $
end


GenericQueryClass FromNode isA Individual with
  parameter
     lnk: attributee
  constraint
     cfn: $ From(lnk,this) $
end

GenericQueryClass ToNode isA Individual with
  parameter
     lnk: attributee
  constraint
     cfn: $ To(lnk,this) $
end



GenericQueryClass ShowBF isA BFModel with
  parameter,required
     bf : BFModel
  constraint
     c1: $ (bf = this) $
end

GenericQueryClass ShowElement isA BFModel with
  required,parameter
     bf: BFModel;
     type: GraphVizType
  computed_attribute
     elem: Element
 constraint
     c1: $ (bf = this) and
           (this contains elem) and
           (elem in type) $
end




GraphVizErd in AnswerFormat with
  forQuery q: ShowBF
  head h: "digraph BF \{"
  pattern p:
"
{ASKquery(ShowElement[{this}/bf,Ellipsenode/type],ELLIPSENODE_FORMAT)}
{ASKquery(ShowElement[{this}/bf,link/type],LINK_FORMAT)}
label=\"Flights Model {this}\\\nCreated by {user} at {transactiontime}\"
fontsize=12;
"
  tail t: "\}"
end

ELLIPSENODE_FORMAT in AnswerFormat with
pattern p: "node [shape=ellipse]; {Foreach( ({this.elem}), (m), {m};)}"
end

LINK_FORMAT in AnswerFormat with
pattern p: "{Foreach( ({this.elem}),(l),{ASKquery(FromNode[{l}/lnk],LABEL)}->{ASKquery(ToNode[{l}/lnk],LABEL)} [len=1.20];\\n)}"
end




```

== Shell output

```text
=== HOW-TO: export-models-as-graphviz-specifications ===

>>> Running ./ConceptBase Tutorial 3/cbtutorial3-all.cbs.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>This is CBShell, the command line interface to ConceptBase.cc
[offline]>[offline]>[offline]>[offline]>[offline]>[offline]>[offline]>Successfully connected to server
Successfully connected to server
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>
# Generated by ConceptBase 8.1.17 at 2026-06-06 20:43:47.426
# Process this file by Graphviz, e.g. 
#    neato -Tpng thisfile.txt > thisfile.png


digraph TrafficLights {
node [shape=box];  gy2; yr2; rg2; gy1; yr1; rg1;
node [shape=circle,fixedsize=true,width=0.9];  green2; yellow2; red2; safe2; safe1; green1; yellow1; red1;
safe2->rg2;
green2->gy2;
yellow2->yr2;
red2->rg2;
safe1->rg1;
green1->gy1;
yellow1->yr1;
red1->rg1;

gy2->yellow2;
rg2->green2;
yr2->safe1;
yr2->red2;
gy1->yellow1;
rg1->green1;
yr1->safe2;
yr1->red1;

overlap=false
label="PetriNet Model TrafficLights\nExtracted from ConceptBase and layed out by Graphviz "
fontsize=12;
}

[localhost:4001]>
# Generated by ConceptBase 8.1.17 at 2026-06-06 20:43:47.426
# Process this file by Graphviz, e.g. 
#    neato -Tpng thisfile.txt > thisfile.png


digraph TrafficLights {
node [shape=box];  gy2; yr2; rg2; gy1; yr1; rg1;
node [shape=circle,fixedsize=true,width=0.9];  green2; yellow2; red2; safe2; safe1; green1; yellow1; red1;
safe2->rg2;
green2->gy2;
yellow2->yr2;
red2->rg2;
safe1->rg1;
green1->gy1;
yellow1->yr1;
red1->rg1;

gy2->yellow2;
rg2->green2;
yr2->safe1;
yr2->red2;
gy1->yellow1;
rg1->green1;
yr1->safe2;
yr1->red1;

overlap=false
label="PetriNet Model TrafficLights\nExtracted from ConceptBase and layed out by Graphviz "
fontsize=12;
}

[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>
>>> Running ./ConceptBase Tutorial 3/cbtutorial3-script1.cbs.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>This is CBShell, the command line interface to ConceptBase.cc
[offline]>[offline]>[offline]>[offline]>[offline]>[offline]>[offline]>Successfully connected to server
Successfully connected to server
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>TrafficLights in ShowElement[TrafficLights/pn,Place/type] with 
   elem
    COMPUTED_elem_id_2413 : red1;
    COMPUTED_elem_id_2418 : yellow1;
    COMPUTED_elem_id_2423 : green1;
    COMPUTED_elem_id_2428 : safe1;
    COMPUTED_elem_id_2435 : safe2;
    COMPUTED_elem_id_2444 : red2;
    COMPUTED_elem_id_2449 : yellow2;
    COMPUTED_elem_id_2454 : green2
end 


[localhost:4001]>TrafficLights in ShowElement[TrafficLights/pn,Place/type] with 
   elem
    COMPUTED_elem_id_2413 : red1;
    COMPUTED_elem_id_2418 : yellow1;
    COMPUTED_elem_id_2423 : green1;
    COMPUTED_elem_id_2428 : safe1;
    COMPUTED_elem_id_2435 : safe2;
    COMPUTED_elem_id_2444 : red2;
    COMPUTED_elem_id_2449 : yellow2;
    COMPUTED_elem_id_2454 : green2
end 


[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>node [shape=circle,fixedsize=true,width=0.9];  green2; yellow2; red2; safe2; safe1; green1; yellow1; red1;
[localhost:4001]>node [shape=circle,fixedsize=true,width=0.9];  green2; yellow2; red2; safe2; safe1; green1; yellow1; red1;
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>yes
[localhost:4001]>yes
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>
>>> Running ./ConceptBase Tutorial 3/cbtutorial3-script2.cbs.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>This is CBShell, the command line interface to ConceptBase.cc
[offline]>[offline]>[offline]>[offline]>[offline]>[offline]>[offline]>Successfully connected to server
Successfully connected to server
[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>
# Generated by ConceptBase 8.1.17 at 2026-06-06 20:43:48.602
# Process this file by Graphviz, e.g. 
#    neato -Tpng thisfile.txt > thisfile.png


digraph TrafficLights {
node [shape=box];  gy2; yr2; rg2; gy1; yr1; rg1;
node [shape=circle,fixedsize=true,width=0.9];  green2; yellow2; red2; safe2; safe1; green1; yellow1; red1;
safe2->rg2;
green2->gy2;
yellow2->yr2;
red2->rg2;
safe1->rg1;
green1->gy1;
yellow1->yr1;
red1->rg1;

gy2->yellow2;
rg2->green2;
yr2->safe1;
yr2->red2;
gy1->yellow1;
rg1->green1;
yr1->safe2;
yr1->red1;

overlap=false
label="PetriNet Model TrafficLights\nExtracted from ConceptBase and layed out by Graphviz "
fontsize=12;
}

[localhost:4001]>
# Generated by ConceptBase 8.1.17 at 2026-06-06 20:43:48.602
# Process this file by Graphviz, e.g. 
#    neato -Tpng thisfile.txt > thisfile.png


digraph TrafficLights {
node [shape=box];  gy2; yr2; rg2; gy1; yr1; rg1;
node [shape=circle,fixedsize=true,width=0.9];  green2; yellow2; red2; safe2; safe1; green1; yellow1; red1;
safe2->rg2;
green2->gy2;
yellow2->yr2;
red2->rg2;
safe1->rg1;
green1->gy1;
yellow1->yr1;
red1->rg1;

gy2->yellow2;
rg2->green2;
yr2->safe1;
yr2->red2;
gy1->yellow1;
rg1->green1;
yr1->safe2;
yr1->red1;

overlap=false
label="PetriNet Model TrafficLights\nExtracted from ConceptBase and layed out by Graphviz "
fontsize=12;
}

[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>[localhost:4001]>
>>> Running ./for ERD diagrams/gvtest.cbs.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>This is CBShell, the command line interface to ConceptBase.cc
[offline]>Successfully connected to server
Successfully connected to server
[localhost:4001]>[localhost:4001]>no
[localhost:4001]>no
[localhost:4001]>no
[localhost:4001]>no
[localhost:4001]>nil
[localhost:4001]>nil
[localhost:4001]>[localhost:4001]>[localhost:4001]>
>>> Telling ./for ERD diagrams/ERD-graphviz.sml.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>Successfully connected to server
[localhost:4001]>no
[localhost:4001]>
>>> Telling ./for ERD diagrams/ERD-graphviz2.sml.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>Successfully connected to server
[localhost:4001]>no
[localhost:4001]>
>>> Telling ./for ERD diagrams/UniversityModel.sml.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>Successfully connected to server
[localhost:4001]>no
[localhost:4001]>
>>> Telling ./for Large Models/BF-viz.sml.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>Successfully connected to server
[localhost:4001]>no
[localhost:4001]>
>>> Telling ./for Large Models/BigFlights.sml.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>Successfully connected to server
[localhost:4001]>no
[localhost:4001]>
>>> Telling ./for Petri Nets/PN-graphviz.sml.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>Successfully connected to server
[localhost:4001]>no
[localhost:4001]>
>>> Telling ./for Petri Nets/PhiloDilemma.sml.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>Successfully connected to server
[localhost:4001]>yes
[localhost:4001]>
>>> Telling ./for Petri Nets/TrafficLights.sml.txt
This is CBShell, the command line interface to ConceptBase.cc
[offline]>Successfully connected to server
[localhost:4001]>yes
[localhost:4001]>
```

== Interpretation

The Nix check completes without CBShell or cbserver errors. Review `yes`/`no` responses in the log for tell outcomes.
