cbforminsert.code=i5.cb.servlets.HTMLFormInsert
cbforminsert.initparams=\
	host=localhost,\
	port=4001,\
	logdir=log

cbformupdate.code=i5.cb.servlets.HTMLFormUpdate
cbformupdate.initparams=\
	host=localhost,\
	port=4001,\
	logdir=log

cbformdelete.code=i5.cb.servlets.HTMLFormDelete
cbformdelete.initparams=\
	host=localhost,\
	port=4001,\
	logdir=log

cbquery.code=i5.cb.servlets.CBQuery
cbquery.initparams=\
    host=localhost,\
    port=4001,\
    logdir=log
    

