#!/usr/bin/env python3
"""Translate German comments and USU identifiers in conceptbase-cc SML files."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMPONENTS = ROOT / "components"

# --- Comment translations (exact line replacements) ---
COMMENT_REPLACEMENTS: list[tuple[str, str]] = [
    (
        "{ ---- Objekte, denen ein grafischer Typ zugeordnet ist ---- }",
        "{ ---- Objects assigned a graphical type ---- }",
    ),
    (
        "{ ---- Klasse X11_Color und die Instanzen; sind natuerlich noch nicht vollstaendig ---- }",
        "{ ---- Class X11_Color and its instances; naturally not yet complete ---- }",
    ),
    ("{ ---- Klasse ATK_Fonts ---- }", "{ ---- Class ATK_Fonts ---- }"),
    ("{ ---- Klasse ATK_TextAlign ---- }", "{ ---- Class ATK_TextAlign ---- }"),
    ("{ ---- Klasse ATK_LineCap ---- }", "{ ---- Class ATK_LineCap ---- }"),
    (
        "{ ---- Klasse X11GraphBrowserPalette mit ihren Inhalten ---- }",
        "{ ---- Class X11GraphBrowserPalette with its contents ---- }",
    ),
    (
        "{ ---- Die Standard grafischen Typen des Graphbrowsers ---- }",
        "{ ---- The standard graphical types of the graph browser ---- }",
    ),
    ("{Art des Kantenanfangs}", "{edge start cap style}"),
    ("{Art des Kantenendes}", "{edge end cap style}"),
    ("{* schlechter *}", "{* worse case *}"),
    ("Daten { hellblaues Rechteck }", "Data { light-blue rectangle }"),
    ("Traeger with { Diskette-Pixmap}", "Carrier with { floppy-disk pixmap }"),
    ("Akteur with {Mensch-Pixmap }", "Actor with { person pixmap }"),
    (
        "Aktion with {ovalnode mit beigen Hintergrund }",
        "Action with { ovalnode with beige background }",
    ),
]

# --- Identifier renames (longest first) ---
IDENT_REPLACEMENTS: list[tuple[str, str]] = [
    # Compound query / class names (longest first)
    ("A_Kundenverantwortlicher!vb_verifiziert", "A_CustomerRepresentative!vb_verifies"),
    ("A_Kundenverantwortlicher!vb_beauftragt", "A_CustomerRepresentative!vb_commissions"),
    ("A_Kundenverantwortlicher!vb_bietet_an", "A_CustomerRepresentative!vb_offers"),
    ("A_Kundenverantwortlicher", "A_CustomerRepresentative"),
    ("A_Projektleiter!pl_projektabrechnung", "A_ProjectLeader!pl_project_billing"),
    ("A_Projektleiter!pl_monatsbericht", "A_ProjectLeader!pl_monthly_report"),
    ("A_Projektleiter!pl_projektanlage", "A_ProjectLeader!pl_project_setup"),
    ("A_Projektleiter!pl_nachweis", "A_ProjectLeader!pl_proof"),
    ("A_Projektleiter!pl_beauftragt", "A_ProjectLeader!pl_commissions"),
    ("A_Projektleiter", "A_ProjectLeader"),
    ("A_KundenPl!kd_bestaetigt", "A_CustomerPL!kd_confirms"),
    ("A_KundenPl", "A_CustomerPL"),
    ("A_ProjContrl!pc_stellt_rechnung", "A_ProjectControl!pc_invoices"),
    ("A_ProjContrl!pc_kopiert_rechnung", "A_ProjectControl!pc_copies_invoice"),
    ("A_ProjContrl!pc_projektstart", "A_ProjectControl!pc_project_start"),
    ("A_ProjContrl!pc_gibt_weiter", "A_ProjectControl!pc_forwards"),
    ("A_ProjContrl!pc_informiert", "A_ProjectControl!pc_informs"),
    ("A_ProjContrl!pc_mahnt", "A_ProjectControl!pc_reminds"),
    ("A_ProjContrl!pc_ablage", "A_ProjectControl!pc_archives"),
    ("A_ProjContrl", "A_ProjectControl"),
    ("A_PersVerantw!pv_monatsbericht", "A_PersonnelManager!pv_monthly_report"),
    ("A_PersVerantw", "A_PersonnelManager"),
    ("A_Personal!pe_gibt_weiter", "A_Personnel!pe_forwards"),
    ("A_Personal!pe_korrigiert", "A_Personnel!pe_corrects"),
    ("A_Personal!pe_verteilt", "A_Personnel!pe_distributes"),
    ("A_Personal!pe_sagt_bescheid", "A_Personnel!pe_notifies"),
    ("A_Personal", "A_Personnel"),
    ("A_Buchhalt!bu_abrechnung", "A_Accounting!bu_settlement"),
    ("A_Buchhalt!bu_zahlt_spesen", "A_Accounting!bu_pays_expenses"),
    ("A_Buchhalt!bu_offene_posten", "A_Accounting!bu_open_items"),
    ("A_Buchhalt", "A_Accounting"),
    ("A_Sekretariat!se_gibt_weiter", "A_Secretariat!se_forwards"),
    ("A_Sekretariat!se_gibt_rechng", "A_Secretariat!se_forwards_invoice"),
    ("A_Sekretariat!se_gibt_sonst", "A_Secretariat!se_forwards_misc"),
    ("A_Sekretariat", "A_Secretariat"),
    ("A_Mitarbeiter!ma_monatsbericht", "A_Employee!ma_monthly_report"),
    ("A_Mitarbeiter!ma_projektabrechnung", "A_Employee!ma_project_billing"),
    ("A_Mitarbeiter", "A_Employee"),
    ("A_Kunde!kd_anfragt", "A_Customer!kd_inquires"),
    ("A_Kunde!kd_beauftragt", "A_Customer!kd_commissions"),
    ("A_Kunde!kd_bezahlt", "A_Customer!kd_pays"),
    ("A_Kunde", "A_Customer"),
    ("A_GL!gl_bestaetigt", "A_Management!gl_confirms"),
    ("A_GL!gl_bestimmt", "A_Management!gl_determines"),
    ("A_GL", "A_Management"),
    ("P_AlleTraegerNichtGefuelltIn", "P_AllCarriersNotFilledIn"),
    ("P_AlleTraegerGefuelltIn", "P_AllCarriersFilledIn"),
    ("P_TraegerNichtGefuelltIn", "P_CarrierNotFilledIn"),
    ("P_TraegerGefuelltIn", "P_CarrierFilledIn"),
    ("P_TraegerEingabe", "P_CarrierInput"),
    ("P_TraegerAusgabe", "P_CarrierOutput"),
    ("P_EinAkteurWirdBeliefert2", "P_OneActorIsSupplied2"),
    ("P_EinAkteurWirdBeliefert", "P_OneActorIsSupplied"),
    ("P_NichtNachfolgerVon", "P_NotSuccessorOf"),
    ("P_NichtVorgaengerVon", "P_NotPredecessorOf"),
    ("P_NachfolgerVon", "P_SuccessorOf"),
    ("P_VorgaengerVon", "P_PredecessorOf"),
    ("P_DatenInputNutzer", "P_DataInputUser"),
    ("P_DatenOutputter", "P_DataOutputter"),
    ("P_DatenInputter", "P_DataInputter"),
    ("P_DatenFalschNutzer", "P_DataWrongUser"),
    ("P_DatenNutzer", "P_DataUser"),
    ("P_ENDE", "P_END"),
    ("AkteurErzeugtOhneBraucht", "ActorCreatesWithoutNeeds"),
    ("AkteurBrauchtOhneErzeugt", "ActorNeedsWithoutCreates"),
    ("AkteurErzeugtUndBraucht", "ActorCreatesAndNeeds"),
    ("AkteurNichtsErzeugt", "ActorCreatesNothing"),
    ("AkteurNichtsBraucht", "ActorNeedsNothing"),
    ("AkteurBelieferung", "ActorSupply"),
    ("AktionenOhneEingabe", "ActionsWithoutInput"),
    ("AktionenOhneAusgabe", "ActionsWithoutOutput"),
    ("AktionenOhneInput", "ActionsWithoutDataInput"),
    ("AktionenOhneOutput", "ActionsWithoutDataOutput"),
    ("AktionenQuellen", "ActionSources"),
    ("AktionenSenken", "ActionSinks"),
    ("DatenInputNiemalsOutput", "DataInputNeverDataOutput"),
    ("DatenInputOhneOutput", "DataInputWithoutDataOutput"),
    ("DatenNichtOutput", "DataNotDataOutput"),
    ("DatenNichtInput", "DataNotDataInput"),
    ("DatenVieleOutputs", "DataManyDataOutputs"),
    ("DatenOhneTraeger", "DataWithoutCarrier"),
    ("TraegerOhneDaten", "CarrierWithoutData"),
    ("BeliefertOhneFolgtAuf", "SuppliesWithoutFollowsAfter"),
    ("FolgtAufOhneBeliefert", "FollowsAfterWithoutSupply"),
    ("BeliefernEinanderMit", "SupplyEachOtherWith"),
    ("BeliefernEinander", "SupplyEachOther"),
    ("WirdMehrfachBeliefert", "MultiplySupplied"),
    ("BeliefertMitNichts", "SuppliesWithNothing"),
    ("UngelieferteTraeger", "UndeliveredCarriers"),
    ("TraegerErzeugtOhneBraucht", "CarrierCreatedWithoutNeeded"),
    ("TraegerBrauchtOhneErzeugt", "CarrierNeededWithoutCreated"),
    ("TraegerGenommenListe", "CarrierTakenList"),
    ("TraegerGegebenListe", "CarrierGivenList"),
    ("TraegerNieGebraucht", "CarrierNeverNeeded"),
    ("TraegerNieErzeugt", "CarrierNeverCreated"),
    ("LiefernOhneErzeugen", "DeliverWithoutCreate"),
    ("ErzeugenOhneLiefern", "CreateWithoutDeliver"),
    ("ErhaltenOhneBrauchen", "ReceiveWithoutNeed"),
    ("BrauchenOhneErhalten", "NeedWithoutReceive"),
    ("ErzeugtOhneGibt", "CreatesWithoutGives"),
    ("BrauchtOhneNimmt", "NeedsWithoutTakes"),
    ("GibtOhneErzeugt", "GivesWithoutCreates"),
    ("NimmtOhneBraucht", "TakesWithoutNeeds"),
    ("InputOhneEingabe", "DataInputWithoutInput"),
    ("EingabeOhneInput", "InputWithoutDataInput"),
    ("OutputOhneAusgabe", "DataOutputWithoutOutput"),
    ("AusgabeOhneOutput", "OutputWithoutDataOutput"),
    ("AusgabeOhneEingabe", "OutputWithoutInput"),
    ("InputOhneNehmen", "DataInputWithoutTaking"),
    ("OutputOhneGeben", "DataOutputWithoutGiving"),
    ("BeliefertKeinen", "SuppliesNobody"),
    ("BeliefertOneWay", "OneWaySupply"),
    ("BeliefertSich", "SuppliesSelf"),
    ("NieBeliefert", "NeverSupplied"),
    ("TF_Kalkulationsblatt", "TF_CalculationSheet"),
    ("TF_ProjektAbrechnung", "TF_ProjectBilling"),
    ("TF_ProjektAuftragMa", "TF_ProjectOrderEmployee"),
    ("TF_ProjektAuftrag", "TF_ProjectOrder"),
    ("TF_ProjektAnlage", "TF_ProjectCreation"),
    ("TF_ProjektAbschluss", "TF_ProjectClosure"),
    ("TF_StatusBericht", "TF_StatusReport"),
    ("TF_MonatsBericht", "TF_MonthlyReport"),
    ("T_KorrekturGespraech", "T_CorrectionMeeting"),
    ("T_SollProjektListe", "T_TargetProjectList"),
    ("T_Kostensaetze", "T_CostRates"),
    ("T_BuchungsListe", "T_BookingList"),
    ("T_SpesenZahlung", "T_ExpensePayment"),
    ("T_SpesenBeleg", "T_ExpenseReceipt"),
    ("T_SonstKosten", "T_MiscCosts"),
    ("T_Auswertungen", "T_Evaluations"),
    ("T_Abwesenheit", "T_Absence"),
    ("T_UmsatzListe", "T_RevenueList"),
    ("T_ProjektOrdner", "T_ProjectFolder"),
    ("T_VersNachweis", "T_InsuranceProof"),
    ("TX_SpesenRechnung", "TX_ExpenseInvoice"),
    ("TX_SpesenZahlung", "TX_ExpensePayment"),
    ("TX_Halbfertige", "TX_SemiFinished"),
    ("T_Halbfertige", "T_SemiFinished"),
    ("T_Zahlung", "T_Payment"),
    ("T_Mahnung", "T_Reminder"),
    ("T_Anfrage", "T_Inquiry"),
    ("T_Angebot", "T_Offer"),
    ("T_Auftrag", "T_Order"),
    ("T_Rechnung", "T_Invoice"),
    ("TW_Rechnung", "TW_Invoice"),
    ("metaTraegerGT", "metaCarrierGT"),
    ("metaAkteurGT", "metaActorGT"),
    ("metaAktionGT", "metaActionGT"),
    ("metaDatenGT", "metaDataGT"),
    ("TraegerGT", "CarrierGT"),
    ("AkteurGT", "ActorGT"),
    ("AktionGT", "ActionGT"),
    ("DatenGT", "DataGT"),
    ("Traeger!enthaelt", "Carrier!contains"),
    ("Akteur!beliefert", "Actor!supplies"),
    ("Akteur!beliefert!mit", "Actor!supplies!via"),
    ("transAggregiertVon", "transAggregatedFrom"),
    ("transFolgtAuf", "transFollowsAfter"),
    ("bearbeitet_von", "processed_by"),
    ("folgt_auf", "follows_after"),
    ("teil_von", "part_of"),
    ("verantwortet", "responsible_for"),
    ("nimmtTraeger", "takesCarrier"),
    ("eingetragen", "registered"),
    ("TraegerZuviel", "CarrierExcess"),
    ("Geschaeftsbereich", "BusinessArea"),
    ("Personalabteilung", "HRDepartment"),
    ("aendereSpesensaetze", "changeExpenseRates"),
    ("abgerechnetWann", "billedWhen"),
    ("istProjektLeiter", "isProjectLeader"),
    ("istInProjekt", "isInProject"),
    ("spesenauszahlung", "expensePayout"),
    ("D_Spesenauszahlung", "D_ExpensePayout"),
    ("D_Spesensaetze", "D_ExpenseRates"),
    ("D_KorrekturInfo", "D_CorrectionInfo"),
    ("D_KundenName", "D_CustomerName"),
    ("D_Mitarbeiter", "D_Employee"),
    ("D_AngebotsLeistung", "D_OfferService"),
    ("D_AngebotsLiestung", "D_OfferService"),
    ("D_AngebotsNummer", "D_OfferNumber"),
    ("D_AngebotsOk", "D_OfferOk"),
    ("D_AngebotUntGL", "D_OfferSigManagement"),
    ("D_AuftragUnt", "D_OrderSignature"),
    ("D_Bezahlt", "D_Paid"),
    ("D_HalbFertigRestaufwand", "D_SemiFinishedRemainingEffort"),
    ("D_HalbFertigSumme", "D_SemiFinishedSum"),
    ("D_KostenSatz", "D_CostRate"),
    ("D_MaUrlaub", "D_EmployeeVacation"),
    ("D_MaName", "D_EmployeeName"),
    ("D_PlName", "D_PLName"),
    ("D_MonIntLeistung", "D_MonthIntService"),
    ("D_MonIntRechnUnt", "D_MonthIntInvoiceSig"),
    ("D_MonIntSachlUnt", "D_MonthIntMaterialSig"),
    ("D_MonIntSpesenSum", "D_MonthIntExpensesSum"),
    ("D_MonIntSpesen", "D_MonthIntExpenses"),
    ("D_MonIntStundenSum", "D_MonthIntHoursSum"),
    ("D_MonIntUntMa", "D_MonthIntSigEmployee"),
    ("D_MonIntUntPv", "D_MonthIntSigPersonnelMgr"),
    ("D_MonZusRechnUnt", "D_MonthSuppInvoiceSig"),
    ("D_MonZusSachlUnt", "D_MonthSuppMaterialSig"),
    ("D_MonZusSchule", "D_MonthSuppSchool"),
    ("D_MonZusSpesen", "D_MonthSuppExpenses"),
    ("D_MonZusUrlaub", "D_MonthSuppVacation"),
    ("D_PerbitSchulung", "D_PerbitTraining"),
    ("D_PerbitUrlaub", "D_PerbitVacation"),
    ("D_ProjAbrBonusExtra", "D_ProjectBillingBonusExtra"),
    ("D_ProjAbrGesStdSum", "D_ProjectBillingTotalHoursSum"),
    ("D_ProjAbrLeistung", "D_ProjectBillingService"),
    ("D_ProjAbrMonat", "D_ProjectBillingMonth"),
    ("D_ProjAbrRechnUnt", "D_ProjectBillingInvoiceSig"),
    ("D_ProjAbrSachlUnt", "D_ProjectBillingMaterialSig"),
    ("D_ProjAbrSpesVorOrt", "D_ProjectBillingOnSiteExpenses"),
    ("D_ProjAbrSpesenSum", "D_ProjectBillingExpensesSum"),
    ("D_ProjAbrSpesen", "D_ProjectBillingExpenses"),
    ("D_ProjAbrStundenSum", "D_ProjectBillingHoursSum"),
    ("D_ProjAbrSumme", "D_ProjectBillingSum"),
    ("D_ProjAbrUntKd", "D_ProjectBillingSigCustomer"),
    ("D_ProjAbrUntMa", "D_ProjectBillingSigEmployee"),
    ("D_ProjAbrUntPl", "D_ProjectBillingSigPL"),
    ("D_ProjAuftPlUnt", "D_ProjectOrderPLSig"),
    ("D_ProjNummer", "D_ProjectNumber"),
    ("D_ProjSollStunden", "D_ProjectTargetHours"),
    ("D_ProjStatFertigSum", "D_ProjectStatusCompleteSum"),
    ("D_ProjStatFertig", "D_ProjectStatusComplete"),
    ("D_ProjStatFestpreis", "D_ProjectStatusFixedPrice"),
    ("D_ProjStatOperativ", "D_ProjectStatusOperative"),
    ("D_ProjStatRechng", "D_ProjectStatusInvoice"),
    ("D_ProjStatUnt", "D_ProjectStatusSignature"),
    ("D_Projekt", "D_Project"),
    ("D_RechngNummer", "D_InvoiceNumber"),
    ("D_RechngUnt", "D_InvoiceSignature"),
    ("D_SollProjektOk", "D_TargetProjectOk"),
    ("D_SonstBetrag", "D_MiscAmount"),
    ("D_SpesBelRechnUnt", "D_ExpenseReceiptInvoiceSig"),
    ("D_SpesBelSachlUnt", "D_ExpenseReceiptMaterialSig"),
    ("D_SpesenBetragNetto", "D_ExpenseAmountNet"),
    ("D_SpesenBetragSum", "D_ExpenseAmountSum"),
    ("D_SpesenBetrag", "D_ExpenseAmount"),
    ("D_KalkStunden", "D_CalcHours"),
    ("D_ProjeNummer", "D_ProjectNumber"),
    ("vonAktion", "fromAction"),
    ("verwendet_in", "used_in"),
    ("folgtAuf", "followsAfter"),
    ("liefertAn", "deliversTo"),
    ("erhaltenVon", "receivedFrom"),
    ("erstmalig", "firstTime"),
    ("letztmalig", "lastTime"),
    ("letzter", "lastOne"),
    ("erster", "firstOne"),
    ("einAus", "oneInOut"),
    ("ingeputtet", "dataInputted"),
    ("outgeputtet", "dataOutputted"),
    ("inDaten", "inData"),
    ("ausDaten", "outData"),
    ("einDaten", "oneData"),
    ("gelesen", "readData"),
    ("geschrieben", "writtenData"),
    ("ohneBraucht", "withoutNeeds"),
    ("nurBraucht", "onlyNeeds"),
    ("nurErzeugt", "onlyCreates"),
    ("nurGibt", "onlyGives"),
    ("bekommt", "receives"),
    ("schlechter", "worseCase"),
    ("unmittelbar", "directly"),
    ("mittelbar", "indirectly"),
    ("aggregiert", "aggregated"),
    ("aggregiertVon", "aggregatedFrom"),
    ("gebucht", "booked"),
    ("bezahlt", "paid"),
    ("korrekturInfo", "correctionInfo"),
    ("kostenSatz", "costRate"),
    ("kundenName", "customerName"),
    ("maUrlaub", "employeeVacation"),
    ("monIntLeistung", "monthIntService"),
    ("monIntRechnUnt", "monthIntInvoiceSig"),
    ("monIntSachlUnt", "monthIntMaterialSig"),
    ("monIntSpesenSum", "monthIntExpensesSum"),
    ("monIntSpesen", "monthIntExpenses"),
    ("monIntStundenSum", "monthIntHoursSum"),
    ("monIntUntMa", "monthIntSigEmployee"),
    ("monIntUntPv", "monthIntSigPersonnelMgr"),
    ("monZusRechnUnt", "monthSuppInvoiceSig"),
    ("monZusSachlUnt", "monthSuppMaterialSig"),
    ("monZusSchule", "monthSuppSchool"),
    ("monZusSpesen", "monthSuppExpenses"),
    ("monZusUrlaub", "monthSuppVacation"),
    ("perbitSchulung", "perbitTraining"),
    ("perbitUrlaub", "perbitVacation"),
    ("projAbrBonusExtra", "projectBillingBonusExtra"),
    ("projAbrGesStdSum", "projectBillingTotalHoursSum"),
    ("projAbrLeistung", "projectBillingService"),
    ("projAbrMonat", "projectBillingMonth"),
    ("projAbrRechnUnt", "projectBillingInvoiceSig"),
    ("projAbrSachlUnt", "projectBillingMaterialSig"),
    ("projAbrSpesVorOrt", "projectBillingOnSiteExpenses"),
    ("projAbrSpesenSum", "projectBillingExpensesSum"),
    ("projAbrSpesen", "projectBillingExpenses"),
    ("projAbrStundenSum", "projectBillingHoursSum"),
    ("projAbrSumme", "projectBillingSum"),
    ("projAbrUntKd", "projectBillingSigCustomer"),
    ("projAbrUntMa", "projectBillingSigEmployee"),
    ("projAbrUntPl", "projectBillingSigPL"),
    ("projAuftPlUnt", "projectOrderPLSig"),
    ("projNummer", "projectNumber"),
    ("projSollStunden", "projectTargetHours"),
    ("projStatFertigSum", "projectStatusCompleteSum"),
    ("projStatFertig", "projectStatusComplete"),
    ("projStatFestpreis", "projectStatusFixedPrice"),
    ("projStatOperativ", "projectStatusOperative"),
    ("projStatRechng", "projectStatusInvoice"),
    ("projStatUnt", "projectStatusSignature"),
    ("rechngNummer", "invoiceNumber"),
    ("rechngUnt", "invoiceSignature"),
    ("sonstBetrag", "miscAmount"),
    ("spesBelRechnUnt", "expenseReceiptInvoiceSig"),
    ("spesBelSachlUnt", "expenseReceiptMaterialSig"),
    ("spesenBetragNetto", "expenseAmountNet"),
    ("spesenBetragSum", "expenseAmountSum"),
    ("spesenBetrag", "expenseAmount"),
    ("angebotUntGL", "offerSigManagement"),
    ("angebotsLeistung", "offerService"),
    ("angebotsNummer", "offerNumber"),
    ("angebotsOk", "offerOk"),
    ("auftragUnt", "orderSignature"),
    ("halbFertigRestaufwand", "semiFinishedRemainingEffort"),
    ("halbFertigSumme", "semiFinishedSum"),
    # Relation / attribute renames on actors (prefix patterns)
    ("pc_stellt_rechnung", "pc_invoices"),
    ("pc_kopiert_rechnung", "pc_copies_invoice"),
    ("pc_projektstart", "pc_project_start"),
    ("pc_gibt_weiter", "pc_forwards"),
    ("pc_informiert", "pc_informs"),
    ("pc_mahnt", "pc_reminds"),
    ("pc_ablage", "pc_archives"),
    ("pe_gibt_weiter", "pe_forwards"),
    ("pe_korrigiert", "pe_corrects"),
    ("pe_verteilt", "pe_distributes"),
    ("pe_sagt_bescheid", "pe_notifies"),
    ("pe_teilt_mit", "pe_shares_with"),
    ("bu_abrechnung", "bu_settlement"),
    ("bu_zahlt_spesen", "bu_pays_expenses"),
    ("bu_offene_posten", "bu_open_items"),
    ("pl_projektanlage", "pl_project_setup"),
    ("pl_beauftragt", "pl_commissions"),
    ("pl_monatsbericht", "pl_monthly_report"),
    ("pl_projektabrechnung", "pl_project_billing"),
    ("pl_nachweis", "pl_proof"),
    ("pv_monatsbericht", "pv_monthly_report"),
    ("se_gibt_weiter", "se_forwards"),
    ("se_gibt_rechng", "se_forwards_invoice"),
    ("se_gibt_sonst", "se_forwards_misc"),
    ("ma_monatsbericht", "ma_monthly_report"),
    ("ma_projektabrechnung", "ma_project_billing"),
    ("gl_bestaetigt", "gl_confirms"),
    ("gl_bestimmt", "gl_determines"),
    ("vb_bietet_an", "vb_offers"),
    ("vb_beauftragt", "vb_commissions"),
    ("vb_verifiziert", "vb_verifies"),
    ("vb_kalkuliert", "vb_calculates"),
    ("kd_anfragt", "kd_inquires"),
    ("kd_beauftragt", "kd_commissions"),
    ("kd_bestaetigt", "kd_confirms"),
    ("kd_bezahlt", "kd_pays"),
    ("kd_fragt_an", "kd_asks"),
    # Core ontology (order: data input/output first, then carrier input/output)
    ("Traeger", "Carrier"),
    ("traeger", "carrier"),
    ("Akteur", "Actor"),
    ("akteur", "actor"),
    ("Aktion", "Action"),
    ("Daten", "Data"),
    ("enthaelt", "contains"),
    ("beliefert", "supplies"),
    ("braucht", "needs"),
    ("erzeugt", "creates"),
    ("eingabe", "input"),
    ("ausgabe", "output"),
    ("nimmt", "takes"),
    ("gibt", "gives"),
    ("liefert", "delivers"),
    ("TF_MonZus", "TF_MonthSupplement"),
]

DATA_FLOW_REPLACEMENTS = [
    (r"attribute\s+input\s*:\s*Daten", "attribute data_input : Daten"),
    (r"attribute\s+output\s*:\s*Daten", "attribute data_output : Daten"),
    (r"attribute\s+input\s*:\s*Data", "attribute data_input : Data"),
    (r"attribute\s+output\s*:\s*Data", "attribute data_output : Data"),
    (r"\(this input ", "(this data_input "),
    (r"\(this output ", "(this data_output "),
    (r"\(a input ", "(a data_input "),
    (r"\(a output ", "(a data_output "),
    (r"\(~verwendet_in input ", "(~used_in data_input "),
    (r"\(~vonAction output ", "(~fromAction data_output "),
    (r" input ~", " data_input ~"),
    (r" output ~", " data_output ~"),
    (r" input d\)", " data_input d)"),
    (r" output d\)", " data_output d)"),
    (r" input this\)", " data_input this)"),
    (r" output this\)", " data_output this)"),
    (r" not \(this input ", " not (this data_input "),
    (r" not \(this output ", " not (this data_output "),
    (r"  input\s*$", "  data_input"),
    (r"  output\s*$", "  data_output"),
]

# `mit` as relation attribute (not SML keyword contexts)
MIT_REPLACEMENTS = [
    ("Actor!supplies!via", "Actor!supplies!via"),  # noop anchor
    (" mit ", " via "),
    ("(this mit ", "(this via "),
    ("(a mit ", "(a via "),
    ("(b mit ", "(b via "),
    ("(x mit ", "(x via "),
    (" and (b mit ", " and (b via "),
    ("attribute\n        mit :", "attribute\n        via :"),
    ("attribute\n    mit :", "attribute\n    via :"),
]


def apply_ident_replacements(text: str) -> str:
    # Rename data-flow input/output before carrier eingabe/ausgabe become input/output.
    for pattern, repl in DATA_FLOW_REPLACEMENTS:
        text = re.sub(pattern, repl, text)
    for old, new in IDENT_REPLACEMENTS:
        text = text.replace(old, new)
    for old, new in MIT_REPLACEMENTS:
        text = text.replace(old, new)
    return text


def apply_comment_replacements(text: str) -> str:
    for old, new in COMMENT_REPLACEMENTS:
        text = text.replace(old, new)
    return text


def process_file(path: Path, content: str, rename_ids: bool) -> bool:
    updated = apply_comment_replacements(content)
    if rename_ids:
        updated = apply_ident_replacements(updated)
    if updated != content:
        path.write_bytes(updated.encode("utf-8", errors="surrogateescape"))
        return True
    return False


def main() -> None:
    touched: list[str] = []
    sml_files = sorted(COMPONENTS.rglob("*.sml"))

    # Pass 1: USU files get full identifier renames
    usu_dir = COMPONENTS / "examples" / "src" / "USU"
    usu_markers = (
        "Traeger", "Akteur", "Aktion", "Daten", "enthaelt", "bearbeitet_von", "transFolgtAuf"
    )
    skip_rename_dirs = {COMPONENTS / "examples" / "src" / "DWQ"}
    for path in sml_files:
        content = path.read_text(encoding="utf-8", errors="surrogateescape")
        if any(sd in path.parents for sd in skip_rename_dirs):
            rename = False
        else:
            rename = (usu_dir in path.parents or path.parent == usu_dir) or any(
                m in content for m in usu_markers
            )
        if process_file(path, content, rename_ids=rename):
            touched.append(str(path.relative_to(ROOT)))

    print(f"Touched {len(touched)} files:")
    for f in touched:
        print(f"  {f}")


if __name__ == "__main__":
    main()
