#!/bin/csh

# CB_HOME is the ConceptBase installation directory
setenv CLASSPATH $CB_HOME/lib/classes/cb.jar':'$CB_HOME/lib/classes/jgl3.1.0.jar

# Use this line, if you are using Java Servlet Development Kit 2.0
#/home/java/JSDK2.0/bin/servletrunner -p 4725 -d `pwd` &

# Use this line, if you are using Java Servlet Development Kit 2.1
/home/java/jsdk2.1/startserver -config default.cfg &

