#!/bin/csh
#
# File:        		goExClient
# Version:     		1.0
# Creation:   		28-Aug-1992, Hans W. Nissen (RWTH)
# Last Change: 	16-Dec-1994, L. Bauer (RWTH)
# Release:     	1
# -----------------------------------------------------------------------------
#
# This csh command file should be used for starting the IPC example client.
#

# Set CB_HOME to the directory where the Concept Base System
# is installed
setenv CB_HOME ~/CB/CB_Work/ProductPOOL

setenv CBS_DIR $CB_HOME/examples/Clients/PrologClient
setenv BIM_DLC_CMD "`which gcc` -c %I"


#*** starting the example client:

$BIM_PROLOG_DIR/bin/BIMprolog $CBS_DIR/ExampleIpcClient 


unsetenv CBS_DIR

#*** That's all!!
