#! /bin/sh
#
# File:         %M%
# Version:      %I%
# Creation:     8-Dec-1995, Christoph Quix (RWTH)
# Last Change:  2 Nov 1995, Rene Soiron (RWTH)
# Date released : %E%  (YY/MM/DD)
#
# SCCS-Source-Pool : %P%
# Date retrieved : %D% (YY/MM/DD)
#
#-------------------------------------
#
# Dieses Skript kopiert die exportierten Dateien unter ProductPOOL
# in die entsprechende Verzeichnisse unter CB_Product
#

CB_ROOT=/home/cbase/CB_NewStruct
CB_POOL=$CB_ROOT/AdminPOOL
CB_ADMIN=$CB_ROOT/CB_Admin
EXPDIR=EXPORT

# Die Verzeichnisse aus denen die Export-Files einfach nach
# CB_ADMIN kopiert werden koennen
NORMAL_EXPORT="bin \
	distrib \
	doc \
	lib \
	utils \
	utils/CB_TestClient \
	utils/CB_TestClient/scripts \
	crontabs"

# Normaler Export: Einfach kopieren
for dir in $NORMAL_EXPORT
do
	cp -p $CB_POOL/$dir/$EXPDIR/* $CB_ADMIN/$dir
done


# HTML-Seiten und PHP-Skripte kopieren
cp -p $CB_POOL/web/CBdoc/$EXPDIR/* /home/www/htdocs/CBdoc/
cp -p $CB_POOL/web/php/$EXPDIR/* /home/www/php4/htdocs/cb/
