#!/bin/sh

DEFAULT_CB_HOME=`dirname $0`

CB_HOME=${CB_HOME:=$DEFAULT_CB_HOME}
export CB_HOME

CB_VARIANT=`"$CB_HOME/bin/CBvariant"`

# default java
JAVAEXEC=java


# We prefer to use one of the following javas; the last one is most preferred

# take /opt/jre6_10 if installed
if [ -x /opt/jre1.6.0_10/bin/java ]; then
  JAVAEXEC=/opt/jre1.6.0_10/bin/java
fi
# take local jdk6_10 if installed
if [ -x $CB_HOME/$CB_VARIANT/jre1.6.0_10/bin/java ]; then
  JAVAEXEC=$CB_HOME/$CB_VARIANT/jre1.6.0_10/bin/java
fi
# take /usr/bin/java if installed (standard location under Linux)
if [ -x /usr/bin/java ]; then
  JAVAEXEC=/usr/bin/java
fi

if [ "$1" ]; then
  exec $JAVAEXEC -Djava.awt.headless=false -DCB_HOME="$CB_HOME" -classpath "$CB_HOME/lib/classes/cb.jar" i5.cb.graph.cbeditor.CBEditor "$@"
else
# start with ohome.gel as argument to let cbgraph connect to a CBserver
  exec $JAVAEXEC -Djava.awt.headless=false -DCB_HOME="$CB_HOME" -classpath "$CB_HOME/lib/classes/cb.jar" i5.cb.graph.cbeditor.CBEditor "$CB_HOME/lib/ohome.gel"
fi



