/* NotificationParser.java */
/* Generated By:JavaCC: Do not edit this line. NotificationParser.java */
package i5.cb.api.notification;

import i5.cb.telos.frame.*;
import java.io.DataOutputStream;
import java.io.ByteArrayOutputStream;
import com.objectspace.jgl.Sequence;
import com.objectspace.jgl.SList;


/**
 * parses notification sent from a ConceptBase server
 * <li> First, construct a NotificationParser object: <br>
 *      <tt> NotificationParser parser = new NotificationParser( System.in ); </tt>
 * <li> Second, call the function that parses up to the nonterminal symbol
 *      you are expecting, generally Notification.
 *      <tt> Notification notification = parser.notification(); </tt>
 * <li> If you want to go on parsing, just repeat calling the function
 *      corresponding to the appropiate nonterminal. For a list of all
 *      nonterminals, see <a href="file:/home/radig/prcs-work/crda/java/i5/cb/api/notification/Notification.html">the grammar of notifications</a>
 * </ul>
 *
 * @author Christoph Radig
 */

public class NotificationParser implements NotificationParserConstants {

///////////////////////////////////////////////////////////////////////////////
// Parser
///////////////////////////////////////////////////////////////////////////////

/**
 * parses a notification message (as part of an ConceptBase ipcanswer message)
 **/
  final public Notification notification() throws ParseException {Notification r;
    jj_consume_token(13);
    r = updateTerms();
    jj_consume_token(14);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
}

/**
 * parses a term that the server sends in response to an ASK with the
 * answer format VIEW
 **/
  final public Sequence askVIEWTerm() throws ParseException {Sequence r;
    jj_consume_token(13);
    r = terms();
    jj_consume_token(14);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
}

  final public Notification updateTerms() throws ParseException {Notification r = new Notification();  // empty list
  UpdateTerm t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:{
      t = updateTerm();
r.add( t );
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 10:{
          ;
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        jj_consume_token(10);
        t = updateTerm();
r.add( t );
      }
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
}

// updateTerms
  final public 

UpdateTerm updateTerm() throws ParseException {Term t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:{
      jj_consume_token(PLUS);
      jj_consume_token(11);
      t = term();
      jj_consume_token(12);
{if ("" != null) return new UpdateTerm( UpdateTerm.PLUS, t );}
      break;
      }
    case MINUS:{
      jj_consume_token(MINUS);
      jj_consume_token(11);
      t = term();
      jj_consume_token(12);
{if ("" != null) return new UpdateTerm( UpdateTerm.MINUS, t );}
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// updateTerm
  final public 

Sequence terms() throws ParseException {Sequence r = new SList();
  Term t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ALPHANUM:
    case NUMBER:
    case SIMPLELABEL:
    case STRINGLABEL:
    case RULELABEL:{
      t = term();
r.add( t );
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 10:{
          ;
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          break label_2;
        }
        jj_consume_token(10);
        t = term();
r.add( t );
      }
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
}

// terms
  final public 

Term term() throws ParseException {Term r;
  Label lView;
    lView = label();
    jj_consume_token(11);
    if (jj_2_1(2)) {
      r = viewTermX(lView);
{if ("" != null) return r;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ALPHANUM:
      case NUMBER:
      case SIMPLELABEL:
      case STRINGLABEL:
      case RULELABEL:{
        r = attributeTermX(lView);
{if ("" != null) return r;}
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

// term
  final public 

ViewTerm viewTerm() throws ParseException {Label lView;
  ViewTerm r;
    lView = label();
    jj_consume_token(11);
    r = viewTermX(lView);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
}

// viewTerm
  final public 

ViewTerm viewTermX(Label lView) throws ParseException {ObjectName o;
    o = objectName();
    jj_consume_token(12);
ViewTerm r;

    if( o instanceof DeriveExp ) {
      DeriveExp de = (DeriveExp) o;
      ObjectName viewName = new DeriveExp( lView, de.getBindings() );
      r = new ViewTerm( viewName, de.getObjectName() );
    }
    else
      r = new ViewTerm( lView, o );

    {if ("" != null) return r;}
    throw new Error("Missing return statement in function");
}

// viewTermX
  final public 

AttributeTerm attributeTerm() throws ParseException {Label lView;
  AttributeTerm r;
    lView = label();
    jj_consume_token(11);
    r = attributeTermX(lView);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
}

// attributeTerm
  final public 

AttributeTerm attributeTermX(Label lView) throws ParseException {Label lAttrCategory, lLabel;
  ObjectName oSource, oDest;
    lAttrCategory = label();
    jj_consume_token(10);
    oSource = objectName();
    jj_consume_token(10);
    lLabel = label();
    jj_consume_token(10);
    oDest = objectName();
    jj_consume_token(12);
AttributeTerm r;

    if( oSource instanceof DeriveExp ) {
      DeriveExp de = (DeriveExp) oSource;
      ObjectName viewName = new DeriveExp( lView, de.getBindings() );
      r = new AttributeTerm( viewName, lAttrCategory, de.getObjectName(), lLabel, oDest );
    }
    else
      r = new AttributeTerm( lView, lAttrCategory, oSource, lLabel, oDest );

    {if ("" != null) return r;}
    throw new Error("Missing return statement in function");
}

// attributeTermX
  final public 

ObjectName objectName() throws ParseException {Label l;
  ObjectName o1, o2;
  String s;
  SList subst;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ALPHANUM:
    case NUMBER:
    case SIMPLELABEL:
    case STRINGLABEL:
    case RULELABEL:{
      l = label();
{if ("" != null) return l;}
      break;
      }
    case SELECT:{
      jj_consume_token(SELECT);
      jj_consume_token(11);
      o1 = objectName();
      jj_consume_token(10);
      s = selector();
      jj_consume_token(10);
      o2 = objectName();
      jj_consume_token(12);
{if ("" != null) return new SelectExp( o1, s, o2 );}
      break;
      }
    case DERIVE:{
      jj_consume_token(DERIVE);
      jj_consume_token(11);
      o1 = objectName();
      jj_consume_token(10);
      jj_consume_token(13);
      subst = substitutions();
      jj_consume_token(14);
      jj_consume_token(12);
{if ("" != null) return new DeriveExp( o1, subst );}
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// objectName
  final public 

String selector() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SELECTOR1:{
      t = jj_consume_token(SELECTOR1);
{if ("" != null) return t.image;}
      break;
      }
    case SELECTOR2:{
      t = jj_consume_token(SELECTOR2);
{if ("" != null) return t.image;}
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// selector
  final public 

SList substitutions() throws ParseException {SList r = new SList();
  Substitution s;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SUBSTITUTE:{
      s = substitution();
r.add( s );
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 10:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_3;
        }
        jj_consume_token(10);
        s = substitution();
r.add( s );
      }
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
}

// substitutions
  final public 

Substitution substitution() throws ParseException {ObjectName o;
  Label l;
    jj_consume_token(SUBSTITUTE);
    jj_consume_token(11);
    o = objectName();
    jj_consume_token(10);
    l = label();
    jj_consume_token(12);
{if ("" != null) return new Substitution( o, l );}
    throw new Error("Missing return statement in function");
}

// substitution
  final public 

Label label() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ALPHANUM:{
      t = jj_consume_token(ALPHANUM);
{if ("" != null) return new Label( t.image );}
      break;
      }
    case NUMBER:{
      t = jj_consume_token(NUMBER);
{if ("" != null) return new Label( t.image );}
      break;
      }
    case SIMPLELABEL:{
      t = jj_consume_token(SIMPLELABEL);
{if ("" != null) return new Label( t.image );}
      break;
      }
    case STRINGLABEL:{
      t = jj_consume_token(STRINGLABEL);
{if ("" != null) return new Label( t.image );}
      break;
      }
    case RULELABEL:{
      t = jj_consume_token(RULELABEL);
{if ("" != null) return new Label( t.image );}
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3R_objectName_294_3_8()
 {
    if (jj_scan_token(DERIVE)) return true;
    if (jj_scan_token(11)) return true;
    return false;
  }

  private boolean jj_3R_objectName_289_3_7()
 {
    if (jj_scan_token(SELECT)) return true;
    if (jj_scan_token(11)) return true;
    return false;
  }

  private boolean jj_3R_objectName_286_3_5()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_objectName_286_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_objectName_289_3_7()) {
    jj_scanpos = xsp;
    if (jj_3R_objectName_294_3_8()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_objectName_286_3_6()
 {
    if (jj_3R_label_342_3_9()) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_viewTermX_213_3_4()) return true;
    return false;
  }

  private boolean jj_3R_label_351_3_14()
 {
    if (jj_scan_token(RULELABEL)) return true;
    return false;
  }

  private boolean jj_3R_viewTermX_213_3_4()
 {
    if (jj_3R_objectName_286_3_5()) return true;
    if (jj_scan_token(12)) return true;
    return false;
  }

  private boolean jj_3R_label_349_3_13()
 {
    if (jj_scan_token(STRINGLABEL)) return true;
    return false;
  }

  private boolean jj_3R_label_347_3_12()
 {
    if (jj_scan_token(SIMPLELABEL)) return true;
    return false;
  }

  private boolean jj_3R_label_344_3_11()
 {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  private boolean jj_3R_label_342_3_9()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_label_342_3_10()) {
    jj_scanpos = xsp;
    if (jj_3R_label_344_3_11()) {
    jj_scanpos = xsp;
    if (jj_3R_label_347_3_12()) {
    jj_scanpos = xsp;
    if (jj_3R_label_349_3_13()) {
    jj_scanpos = xsp;
    if (jj_3R_label_351_3_14()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_label_342_3_10()
 {
    if (jj_scan_token(ALPHANUM)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public NotificationParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[11];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x400,0x6,0x6,0x400,0x141a0000,0x141a0000,0x141a0018,0xc0,0x400,0x20,0x141a0000,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public NotificationParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public NotificationParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new NotificationParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public NotificationParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new NotificationParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new NotificationParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public NotificationParser(NotificationParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(NotificationParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[29];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 11; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 29; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 1; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}  // class NotificationParser

