/* Generated By:JavaCC: Do not edit this line. NotificationParserConstants.java */
package i5.cb.api.notification;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NotificationParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 1;
  /** RegularExpression Id. */
  int MINUS = 2;
  /** RegularExpression Id. */
  int SELECT = 3;
  /** RegularExpression Id. */
  int DERIVE = 4;
  /** RegularExpression Id. */
  int SUBSTITUTE = 5;
  /** RegularExpression Id. */
  int SELECTOR1 = 6;
  /** RegularExpression Id. */
  int SELECTOR2 = 7;
  /** RegularExpression Id. */
  int ALPHANUM = 17;
  /** RegularExpression Id. */
  int Num = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int SIMPLELABEL = 20;
  /** RegularExpression Id. */
  int STRINGLABEL = 26;
  /** RegularExpression Id. */
  int RULELABEL = 28;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinString = 1;
  /** Lexical state. */
  int WithinRule = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"plus\"",
    "\"minus\"",
    "\"select\"",
    "\"derive\"",
    "\"substitute\"",
    "<SELECTOR1>",
    "<SELECTOR2>",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"/\"",
    "\"_\"",
    "<ALPHANUM>",
    "<Num>",
    "<NUMBER>",
    "<SIMPLELABEL>",
    "\"\\\"\"",
    "\"$\"",
    "<token of kind 23>",
    "\"\\\\\\\"\"",
    "\"\\\\\\\\\"",
    "\"\\\"\"",
    "<token of kind 27>",
    "\"$\"",
  };

}
